// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BudgetSummaryPublicSchema = {
    properties: {
        level: {
            type: 'string',
            maxLength: 20,
            title: 'Level'
        },
        revenue_limit: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Revenue Limit'
        },
        total_revenue_allocated: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Revenue Allocated',
            default: '0.00'
        },
        total_budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Budget Bac',
            default: '0.00'
        },
        total_revenue_plan: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Revenue Plan',
            default: '0.00'
        },
        project_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        wbe_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Wbe Id'
        },
        calculated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Calculated At'
        },
        remaining_revenue: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Remaining Revenue',
            description: 'Calculate remaining revenue (revenue_limit - total_revenue_allocated).',
            readOnly: true
        },
        revenue_utilization_percent: {
            type: 'number',
            title: 'Revenue Utilization Percent',
            description: 'Calculate revenue utilization percentage.',
            readOnly: true
        }
    },
    type: 'object',
    required: ['level', 'revenue_limit', 'remaining_revenue', 'revenue_utilization_percent'],
    title: 'BudgetSummaryPublic',
    description: 'Public schema for budget summary response.'
} as const;

export const CostElementCreateSchema = {
    properties: {
        department_code: {
            type: 'string',
            maxLength: 50,
            title: 'Department Code'
        },
        department_name: {
            type: 'string',
            maxLength: 100,
            title: 'Department Name'
        },
        budget_bac: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Budget Bac',
            default: '0.00'
        },
        revenue_plan: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Revenue Plan',
            default: '0.00'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'planned'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        },
        cost_element_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Type Id'
        }
    },
    type: 'object',
    required: ['department_code', 'department_name', 'wbe_id', 'cost_element_type_id'],
    title: 'CostElementCreate',
    description: 'Schema for creating a new cost element.'
} as const;

export const CostElementPublicSchema = {
    properties: {
        department_code: {
            type: 'string',
            maxLength: 50,
            title: 'Department Code'
        },
        department_name: {
            type: 'string',
            maxLength: 100,
            title: 'Department Name'
        },
        budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Budget Bac',
            default: '0.00'
        },
        revenue_plan: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Revenue Plan',
            default: '0.00'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'planned'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        },
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        },
        cost_element_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Type Id'
        }
    },
    type: 'object',
    required: ['department_code', 'department_name', 'cost_element_id', 'wbe_id', 'cost_element_type_id'],
    title: 'CostElementPublic',
    description: 'Public cost element schema for API responses.'
} as const;

export const CostElementScheduleBaseSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        progression_type: {
            type: 'string',
            maxLength: 50,
            title: 'Progression Type'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['start_date', 'end_date', 'progression_type'],
    title: 'CostElementScheduleBase',
    description: 'Base cost element schedule schema with common fields.'
} as const;

export const CostElementSchedulePublicSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        progression_type: {
            type: 'string',
            maxLength: 50,
            title: 'Progression Type'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        schedule_id: {
            type: 'string',
            format: 'uuid',
            title: 'Schedule Id'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        },
        baseline_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Baseline Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['start_date', 'end_date', 'progression_type', 'schedule_id', 'cost_element_id', 'created_by_id', 'created_at', 'updated_at'],
    title: 'CostElementSchedulePublic',
    description: 'Public cost element schedule schema for API responses.'
} as const;

export const CostElementScheduleUpdateSchema = {
    properties: {
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        progression_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progression Type'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CostElementScheduleUpdate',
    description: 'Schema for updating a cost element schedule.'
} as const;

export const CostElementTypePublicSchema = {
    properties: {
        type_code: {
            type: 'string',
            maxLength: 50,
            title: 'Type Code'
        },
        type_name: {
            type: 'string',
            maxLength: 200,
            title: 'Type Name'
        },
        category_type: {
            type: 'string',
            maxLength: 50,
            title: 'Category Type'
        },
        tracks_hours: {
            type: 'boolean',
            title: 'Tracks Hours',
            default: false
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        cost_element_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Type Id'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        department_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Code'
        },
        department_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['type_code', 'type_name', 'category_type', 'cost_element_type_id', 'created_at', 'updated_at'],
    title: 'CostElementTypePublic',
    description: 'Public cost element type schema for API responses.'
} as const;

export const CostElementTypesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CostElementTypePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CostElementTypesPublic',
    description: 'Schema for list of cost element types.'
} as const;

export const CostElementUpdateSchema = {
    properties: {
        department_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Code'
        },
        department_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Name'
        },
        budget_bac: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Bac'
        },
        revenue_plan: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revenue Plan'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CostElementUpdate',
    description: 'Schema for updating a cost element.'
} as const;

export const CostElementWithSchedulePublicSchema = {
    properties: {
        department_code: {
            type: 'string',
            maxLength: 50,
            title: 'Department Code'
        },
        department_name: {
            type: 'string',
            maxLength: 100,
            title: 'Department Name'
        },
        budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Budget Bac',
            default: '0.00'
        },
        revenue_plan: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Revenue Plan',
            default: '0.00'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'planned'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        },
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        },
        cost_element_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Type Id'
        },
        schedule: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CostElementSchedulePublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['department_code', 'department_name', 'cost_element_id', 'wbe_id', 'cost_element_type_id'],
    title: 'CostElementWithSchedulePublic',
    description: 'Public cost element schema with nested schedule for API responses.'
} as const;

export const CostElementsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CostElementPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CostElementsPublic',
    description: 'Schema for list of cost elements.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'Generic message response.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: 'Password reset request.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        project_name: {
            type: 'string',
            maxLength: 200,
            title: 'Project Name'
        },
        customer_name: {
            type: 'string',
            maxLength: 200,
            title: 'Customer Name'
        },
        contract_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Contract Value',
            default: '0.00'
        },
        project_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Code'
        },
        pricelist_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pricelist Code'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        planned_completion_date: {
            type: 'string',
            format: 'date',
            title: 'Planned Completion Date'
        },
        actual_completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Completion Date'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'active'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        project_manager_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Manager Id'
        }
    },
    type: 'object',
    required: ['project_name', 'customer_name', 'start_date', 'planned_completion_date', 'project_manager_id'],
    title: 'ProjectCreate',
    description: 'Schema for creating a new project.'
} as const;

export const ProjectPublicSchema = {
    properties: {
        project_name: {
            type: 'string',
            maxLength: 200,
            title: 'Project Name'
        },
        customer_name: {
            type: 'string',
            maxLength: 200,
            title: 'Customer Name'
        },
        contract_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Contract Value',
            default: '0.00'
        },
        project_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Code'
        },
        pricelist_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pricelist Code'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        planned_completion_date: {
            type: 'string',
            format: 'date',
            title: 'Planned Completion Date'
        },
        actual_completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Completion Date'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'active'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        project_manager_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Manager Id'
        }
    },
    type: 'object',
    required: ['project_name', 'customer_name', 'start_date', 'planned_completion_date', 'project_id', 'project_manager_id'],
    title: 'ProjectPublic',
    description: 'Public project schema for API responses.'
} as const;

export const ProjectTemplateSchema = {
    properties: {
        project: {
            additionalProperties: true,
            type: 'object',
            title: 'Project'
        },
        wbes: {
            items: {
                '$ref': '#/components/schemas/WBETemplateItem'
            },
            type: 'array',
            title: 'Wbes',
            default: []
        }
    },
    type: 'object',
    required: ['project'],
    title: 'ProjectTemplate',
    description: 'Template for creating a complete project hierarchy.'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        project_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Name'
        },
        customer_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Name'
        },
        contract_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contract Value'
        },
        project_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Code'
        },
        pricelist_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pricelist Code'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        planned_completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Planned Completion Date'
        },
        actual_completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Completion Date'
        },
        project_manager_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Manager Id'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'ProjectUpdate',
    description: 'Schema for updating a project.'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic',
    description: 'Schema for list of projects.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'JSON payload containing access token.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: 'Schema for password update.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 200,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'controller'
        },
        department: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: 'Schema for creating a new user.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 200,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'controller'
        },
        department: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic',
    description: 'Public user schema for API responses.'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 200,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'Schema for user registration.'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['admin', 'project_manager', 'department_manager', 'controller', 'executive_viewer'],
    title: 'UserRole',
    description: 'User role enumeration.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserRole'
                },
                {
                    type: 'null'
                }
            ]
        },
        department: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Schema for updating a user.'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: 'Schema for updating own user profile.'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'Schema for list of users.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WBECreateSchema = {
    properties: {
        machine_type: {
            type: 'string',
            maxLength: 100,
            title: 'Machine Type'
        },
        serial_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Serial Number'
        },
        contracted_delivery_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contracted Delivery Date'
        },
        revenue_allocation: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Revenue Allocation',
            default: '0.00'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'designing'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        }
    },
    type: 'object',
    required: ['machine_type', 'project_id'],
    title: 'WBECreate',
    description: 'Schema for creating a new WBE.'
} as const;

export const WBEPublicSchema = {
    properties: {
        machine_type: {
            type: 'string',
            maxLength: 100,
            title: 'Machine Type'
        },
        serial_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Serial Number'
        },
        contracted_delivery_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contracted Delivery Date'
        },
        revenue_allocation: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Revenue Allocation',
            default: '0.00'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'designing'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        }
    },
    type: 'object',
    required: ['machine_type', 'wbe_id', 'project_id'],
    title: 'WBEPublic',
    description: 'Public WBE schema for API responses.'
} as const;

export const WBETemplateItemSchema = {
    properties: {
        wbe: {
            additionalProperties: true,
            type: 'object',
            title: 'Wbe'
        },
        cost_elements: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Cost Elements',
            default: []
        }
    },
    type: 'object',
    required: ['wbe'],
    title: 'WBETemplateItem',
    description: 'WBE with nested cost elements.'
} as const;

export const WBEUpdateSchema = {
    properties: {
        machine_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Machine Type'
        },
        serial_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Serial Number'
        },
        contracted_delivery_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contracted Delivery Date'
        },
        revenue_allocation: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revenue Allocation'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'WBEUpdate',
    description: 'Schema for updating a WBE.'
} as const;

export const WBEsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WBEPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WBEsPublic',
    description: 'Schema for list of WBEs.'
} as const;