// This file is auto-generated by @hey-api/openapi-ts

export const BaselineCostElementWithCostElementPublicSchema = {
    properties: {
        budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Budget Bac',
            default: '0.00'
        },
        revenue_plan: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Revenue Plan',
            default: '0.00'
        },
        actual_ac: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Ac'
        },
        forecast_eac: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Forecast Eac'
        },
        earned_ev: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Earned Ev'
        },
        percent_complete: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Percent Complete'
        },
        planned_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Planned Value',
            default: '0.00'
        },
        baseline_cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Baseline Cost Element Id'
        },
        baseline_id: {
            type: 'string',
            format: 'uuid',
            title: 'Baseline Id'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        department_code: {
            type: 'string',
            maxLength: 50,
            title: 'Department Code'
        },
        department_name: {
            type: 'string',
            maxLength: 100,
            title: 'Department Name'
        },
        cost_element_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Type Id'
        },
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        },
        wbe_machine_type: {
            type: 'string',
            maxLength: 100,
            title: 'Wbe Machine Type'
        },
        schedule_start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schedule Start Date'
        },
        schedule_end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schedule End Date'
        },
        schedule_progression_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schedule Progression Type'
        },
        schedule_registration_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schedule Registration Date'
        },
        schedule_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schedule Description'
        },
        schedule_notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Schedule Notes'
        }
    },
    type: 'object',
    required: ['baseline_cost_element_id', 'baseline_id', 'cost_element_id', 'created_at', 'department_code', 'department_name', 'cost_element_type_id', 'wbe_id', 'wbe_machine_type'],
    title: 'BaselineCostElementWithCostElementPublic',
    description: 'Public baseline cost element schema with CostElement fields for API responses.'
} as const;

export const BaselineCostElementsByWBEPublicSchema = {
    properties: {
        baseline_id: {
            type: 'string',
            format: 'uuid',
            title: 'Baseline Id'
        },
        wbes: {
            items: {
                '$ref': '#/components/schemas/WBEWithBaselineCostElementsPublic'
            },
            type: 'array',
            title: 'Wbes'
        }
    },
    type: 'object',
    required: ['baseline_id'],
    title: 'BaselineCostElementsByWBEPublic',
    description: 'Public schema for baseline cost elements grouped by WBE.'
} as const;

export const BaselineCostElementsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BaselineCostElementWithCostElementPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            minimum: 0,
            title: 'Count',
            default: 0
        }
    },
    type: 'object',
    title: 'BaselineCostElementsPublic',
    description: 'Public schema for paginated list of baseline cost elements.'
} as const;

export const BaselineLogBaseSchema = {
    properties: {
        baseline_type: {
            type: 'string',
            maxLength: 50,
            title: 'Baseline Type'
        },
        baseline_date: {
            type: 'string',
            format: 'date',
            title: 'Baseline Date'
        },
        milestone_type: {
            type: 'string',
            maxLength: 100,
            title: 'Milestone Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_cancelled: {
            type: 'boolean',
            title: 'Is Cancelled',
            default: false
        },
        department: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        is_pmb: {
            type: 'boolean',
            title: 'Is Pmb',
            default: false
        }
    },
    type: 'object',
    required: ['baseline_type', 'baseline_date', 'milestone_type'],
    title: 'BaselineLogBase',
    description: 'Base baseline log schema with common fields.'
} as const;

export const BaselineLogPublicSchema = {
    properties: {
        baseline_type: {
            type: 'string',
            maxLength: 50,
            title: 'Baseline Type'
        },
        baseline_date: {
            type: 'string',
            format: 'date',
            title: 'Baseline Date'
        },
        milestone_type: {
            type: 'string',
            maxLength: 100,
            title: 'Milestone Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_cancelled: {
            type: 'boolean',
            title: 'Is Cancelled',
            default: false
        },
        department: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        is_pmb: {
            type: 'boolean',
            title: 'Is Pmb',
            default: false
        },
        baseline_id: {
            type: 'string',
            format: 'uuid',
            title: 'Baseline Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['baseline_type', 'baseline_date', 'milestone_type', 'baseline_id', 'project_id', 'created_by_id', 'created_at'],
    title: 'BaselineLogPublic',
    description: 'Public baseline log schema for API responses.'
} as const;

export const BaselineLogUpdateSchema = {
    properties: {
        baseline_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Baseline Type'
        },
        baseline_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Baseline Date'
        },
        milestone_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Milestone Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_cancelled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Cancelled'
        },
        department: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        is_pmb: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Pmb'
        }
    },
    type: 'object',
    title: 'BaselineLogUpdate',
    description: 'Schema for updating a baseline log entry.'
} as const;

export const BaselineSummaryPublicSchema = {
    properties: {
        snapshot_id: {
            type: 'string',
            format: 'uuid',
            title: 'Snapshot Id'
        },
        baseline_id: {
            type: 'string',
            format: 'uuid',
            title: 'Baseline Id'
        },
        baseline_date: {
            type: 'string',
            format: 'date',
            title: 'Baseline Date'
        },
        milestone_type: {
            type: 'string',
            title: 'Milestone Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        total_budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Budget Bac'
        },
        total_revenue_plan: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Revenue Plan'
        },
        total_planned_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Planned Value'
        },
        total_actual_ac: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Actual Ac'
        },
        total_forecast_eac: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Forecast Eac'
        },
        total_earned_ev: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Earned Ev'
        },
        cost_element_count: {
            type: 'integer',
            minimum: 0,
            title: 'Cost Element Count',
            default: 0
        }
    },
    type: 'object',
    required: ['snapshot_id', 'baseline_id', 'baseline_date', 'milestone_type', 'total_budget_bac', 'total_revenue_plan', 'total_planned_value'],
    title: 'BaselineSummaryPublic',
    description: 'Public schema for baseline summary with aggregated values.'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BudgetSummaryPublicSchema = {
    properties: {
        level: {
            type: 'string',
            maxLength: 20,
            title: 'Level'
        },
        revenue_limit: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Revenue Limit'
        },
        total_revenue_allocated: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Revenue Allocated',
            default: '0.00'
        },
        total_budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Budget Bac',
            default: '0.00'
        },
        total_revenue_plan: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Revenue Plan',
            default: '0.00'
        },
        project_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        wbe_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Wbe Id'
        },
        calculated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Calculated At'
        },
        remaining_revenue: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Remaining Revenue',
            description: 'Calculate remaining revenue (revenue_limit - total_revenue_allocated).',
            readOnly: true
        },
        revenue_utilization_percent: {
            type: 'number',
            title: 'Revenue Utilization Percent',
            description: 'Calculate revenue utilization percentage.',
            readOnly: true
        }
    },
    type: 'object',
    required: ['level', 'revenue_limit', 'remaining_revenue', 'revenue_utilization_percent'],
    title: 'BudgetSummaryPublic',
    description: 'Public schema for budget summary response.'
} as const;

export const CostCategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CostCategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CostCategoriesPublic',
    description: 'Public cost categories list schema.'
} as const;

export const CostCategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        code: {
            type: 'string',
            title: 'Code'
        }
    },
    type: 'object',
    required: ['name', 'code'],
    title: 'CostCategoryPublic',
    description: 'Public cost category schema for API responses.'
} as const;

export const CostElementCreateSchema = {
    properties: {
        department_code: {
            type: 'string',
            maxLength: 50,
            title: 'Department Code'
        },
        department_name: {
            type: 'string',
            maxLength: 100,
            title: 'Department Name'
        },
        budget_bac: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Budget Bac',
            default: '0.00'
        },
        revenue_plan: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Revenue Plan',
            default: '0.00'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'planned'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        },
        cost_element_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Type Id'
        }
    },
    type: 'object',
    required: ['department_code', 'department_name', 'wbe_id', 'cost_element_type_id'],
    title: 'CostElementCreate',
    description: 'Schema for creating a new cost element.'
} as const;

export const CostElementPublicSchema = {
    properties: {
        department_code: {
            type: 'string',
            maxLength: 50,
            title: 'Department Code'
        },
        department_name: {
            type: 'string',
            maxLength: 100,
            title: 'Department Name'
        },
        budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Budget Bac',
            default: '0.00'
        },
        revenue_plan: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Revenue Plan',
            default: '0.00'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'planned'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        },
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        },
        cost_element_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Type Id'
        }
    },
    type: 'object',
    required: ['department_code', 'department_name', 'cost_element_id', 'wbe_id', 'cost_element_type_id'],
    title: 'CostElementPublic',
    description: 'Public cost element schema for API responses.'
} as const;

export const CostElementScheduleBaseSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        progression_type: {
            type: 'string',
            maxLength: 50,
            title: 'Progression Type'
        },
        registration_date: {
            type: 'string',
            format: 'date',
            title: 'Registration Date'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['start_date', 'end_date', 'progression_type'],
    title: 'CostElementScheduleBase',
    description: 'Base cost element schedule schema with common fields.'
} as const;

export const CostElementSchedulePublicSchema = {
    properties: {
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        progression_type: {
            type: 'string',
            maxLength: 50,
            title: 'Progression Type'
        },
        registration_date: {
            type: 'string',
            format: 'date',
            title: 'Registration Date'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        schedule_id: {
            type: 'string',
            format: 'uuid',
            title: 'Schedule Id'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        },
        baseline_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Baseline Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['start_date', 'end_date', 'progression_type', 'schedule_id', 'cost_element_id', 'created_by_id', 'created_at', 'updated_at'],
    title: 'CostElementSchedulePublic',
    description: 'Public cost element schedule schema for API responses.'
} as const;

export const CostElementScheduleUpdateSchema = {
    properties: {
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        progression_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progression Type'
        },
        registration_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Date'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CostElementScheduleUpdate',
    description: 'Schema for updating a cost element schedule.'
} as const;

export const CostElementTypePublicSchema = {
    properties: {
        type_code: {
            type: 'string',
            maxLength: 50,
            title: 'Type Code'
        },
        type_name: {
            type: 'string',
            maxLength: 200,
            title: 'Type Name'
        },
        category_type: {
            type: 'string',
            maxLength: 50,
            title: 'Category Type'
        },
        tracks_hours: {
            type: 'boolean',
            title: 'Tracks Hours',
            default: false
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        cost_element_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Type Id'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        department_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Code'
        },
        department_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['type_code', 'type_name', 'category_type', 'cost_element_type_id', 'created_at', 'updated_at'],
    title: 'CostElementTypePublic',
    description: 'Public cost element type schema for API responses.'
} as const;

export const CostElementTypesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CostElementTypePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CostElementTypesPublic',
    description: 'Schema for list of cost element types.'
} as const;

export const CostElementUpdateSchema = {
    properties: {
        department_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Code'
        },
        department_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Name'
        },
        budget_bac: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Bac'
        },
        revenue_plan: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revenue Plan'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CostElementUpdate',
    description: 'Schema for updating a cost element.'
} as const;

export const CostElementWithSchedulePublicSchema = {
    properties: {
        department_code: {
            type: 'string',
            maxLength: 50,
            title: 'Department Code'
        },
        department_name: {
            type: 'string',
            maxLength: 100,
            title: 'Department Name'
        },
        budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Budget Bac',
            default: '0.00'
        },
        revenue_plan: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Revenue Plan',
            default: '0.00'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'planned'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        },
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        },
        cost_element_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Type Id'
        },
        schedule: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CostElementSchedulePublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['department_code', 'department_name', 'cost_element_id', 'wbe_id', 'cost_element_type_id'],
    title: 'CostElementWithSchedulePublic',
    description: 'Public cost element schema with nested schedule for API responses.'
} as const;

export const CostElementsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CostElementPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CostElementsPublic',
    description: 'Schema for list of cost elements.'
} as const;

export const CostRegistrationCreateSchema = {
    properties: {
        registration_date: {
            type: 'string',
            format: 'date',
            title: 'Registration Date'
        },
        amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Amount',
            default: '0.00'
        },
        cost_category: {
            type: 'string',
            maxLength: 50,
            title: 'Cost Category'
        },
        invoice_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invoice Number'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        is_quality_cost: {
            type: 'boolean',
            title: 'Is Quality Cost',
            default: false
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        }
    },
    type: 'object',
    required: ['registration_date', 'cost_category', 'description', 'cost_element_id'],
    title: 'CostRegistrationCreate',
    description: `Schema for creating a new cost registration.

Note: created_by_id is set automatically by the API from current_user.`
} as const;

export const CostRegistrationPublicSchema = {
    properties: {
        registration_date: {
            type: 'string',
            format: 'date',
            title: 'Registration Date'
        },
        amount: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Amount',
            default: '0.00'
        },
        cost_category: {
            type: 'string',
            maxLength: 50,
            title: 'Cost Category'
        },
        invoice_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invoice Number'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        is_quality_cost: {
            type: 'boolean',
            title: 'Is Quality Cost',
            default: false
        },
        cost_registration_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Registration Id'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        last_modified_at: {
            type: 'string',
            format: 'date-time',
            title: 'Last Modified At'
        }
    },
    type: 'object',
    required: ['registration_date', 'cost_category', 'description', 'cost_registration_id', 'cost_element_id', 'created_by_id', 'created_at', 'last_modified_at'],
    title: 'CostRegistrationPublic',
    description: 'Public cost registration schema for API responses.'
} as const;

export const CostRegistrationUpdateSchema = {
    properties: {
        registration_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Date'
        },
        amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount'
        },
        cost_category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cost Category'
        },
        invoice_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invoice Number'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_quality_cost: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Quality Cost'
        }
    },
    type: 'object',
    title: 'CostRegistrationUpdate',
    description: 'Schema for updating a cost registration.'
} as const;

export const CostRegistrationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CostRegistrationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CostRegistrationsPublic',
    description: 'Public cost registrations list schema.'
} as const;

export const CostSummaryPublicSchema = {
    properties: {
        level: {
            type: 'string',
            maxLength: 20,
            title: 'Level'
        },
        total_cost: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Cost',
            default: '0.00'
        },
        budget_bac: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Budget Bac'
        },
        cost_registration_count: {
            type: 'integer',
            minimum: 0,
            title: 'Cost Registration Count',
            default: 0
        },
        cost_element_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cost Element Id'
        },
        wbe_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Wbe Id'
        },
        project_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        calculated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Calculated At'
        },
        cost_percentage_of_budget: {
            type: 'number',
            title: 'Cost Percentage Of Budget',
            description: 'Calculate cost percentage of budget (total_cost / budget_bac) * 100.',
            readOnly: true
        }
    },
    type: 'object',
    required: ['level', 'cost_percentage_of_budget'],
    title: 'CostSummaryPublic',
    description: 'Public schema for cost summary response.'
} as const;

export const CostTimelinePointPublicSchema = {
    properties: {
        point_date: {
            type: 'string',
            format: 'date',
            title: 'Point Date'
        },
        cumulative_cost: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Cumulative Cost'
        },
        period_cost: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Period Cost'
        }
    },
    type: 'object',
    required: ['point_date', 'cumulative_cost', 'period_cost'],
    title: 'CostTimelinePointPublic',
    description: 'Public schema for a single cost timeline point.'
} as const;

export const CostTimelinePublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CostTimelinePointPublic'
            },
            type: 'array',
            title: 'Data'
        },
        total_cost: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Cost',
            default: '0.00'
        }
    },
    type: 'object',
    title: 'CostTimelinePublic',
    description: 'Public schema for cost timeline response.'
} as const;

export const EarnedValueCostElementPublicSchema = {
    properties: {
        level: {
            type: 'string',
            maxLength: 20,
            title: 'Level'
        },
        control_date: {
            type: 'string',
            format: 'date',
            title: 'Control Date'
        },
        earned_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Earned Value',
            default: '0.00'
        },
        percent_complete: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Percent Complete',
            default: '0.0000'
        },
        budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Budget Bac',
            default: '0.00'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        }
    },
    type: 'object',
    required: ['level', 'control_date', 'cost_element_id'],
    title: 'EarnedValueCostElementPublic',
    description: 'Earned value response for cost elements.'
} as const;

export const EarnedValueEntriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/EarnedValueEntryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'EarnedValueEntriesPublic',
    description: 'Public earned value entries list schema.'
} as const;

export const EarnedValueEntryCreateSchema = {
    properties: {
        completion_date: {
            type: 'string',
            format: 'date',
            title: 'Completion Date'
        },
        percent_complete: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Percent Complete',
            default: '0.00'
        },
        earned_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Earned Value'
        },
        deliverables: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deliverables'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        }
    },
    type: 'object',
    required: ['completion_date', 'cost_element_id'],
    title: 'EarnedValueEntryCreate',
    description: `Schema for creating a new earned value entry.

Note: created_by_id is set automatically by the API from current_user.`
} as const;

export const EarnedValueEntryPublicSchema = {
    properties: {
        completion_date: {
            type: 'string',
            format: 'date',
            title: 'Completion Date'
        },
        percent_complete: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Percent Complete',
            default: '0.00'
        },
        earned_value: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Earned Value'
        },
        deliverables: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deliverables'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        earned_value_id: {
            type: 'string',
            format: 'uuid',
            title: 'Earned Value Id'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        last_modified_at: {
            type: 'string',
            format: 'date-time',
            title: 'Last Modified At'
        }
    },
    type: 'object',
    required: ['completion_date', 'earned_value_id', 'cost_element_id', 'created_by_id', 'created_at', 'last_modified_at'],
    title: 'EarnedValueEntryPublic',
    description: 'Public earned value entry schema for API responses.'
} as const;

export const EarnedValueEntryUpdateSchema = {
    properties: {
        completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completion Date'
        },
        percent_complete: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Percent Complete'
        },
        earned_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Earned Value'
        },
        deliverables: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deliverables'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'EarnedValueEntryUpdate',
    description: 'Schema for updating an earned value entry.'
} as const;

export const EarnedValueProjectPublicSchema = {
    properties: {
        level: {
            type: 'string',
            maxLength: 20,
            title: 'Level'
        },
        control_date: {
            type: 'string',
            format: 'date',
            title: 'Control Date'
        },
        earned_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Earned Value',
            default: '0.00'
        },
        percent_complete: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Percent Complete',
            default: '0.0000'
        },
        budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Budget Bac',
            default: '0.00'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        }
    },
    type: 'object',
    required: ['level', 'control_date', 'project_id'],
    title: 'EarnedValueProjectPublic',
    description: 'Earned value response for projects.'
} as const;

export const EarnedValueWBEPublicSchema = {
    properties: {
        level: {
            type: 'string',
            maxLength: 20,
            title: 'Level'
        },
        control_date: {
            type: 'string',
            format: 'date',
            title: 'Control Date'
        },
        earned_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Earned Value',
            default: '0.00'
        },
        percent_complete: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Percent Complete',
            default: '0.0000'
        },
        budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Budget Bac',
            default: '0.00'
        },
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        }
    },
    type: 'object',
    required: ['level', 'control_date', 'wbe_id'],
    title: 'EarnedValueWBEPublic',
    description: 'Earned value response for WBEs.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'Generic message response.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: 'Password reset request.'
} as const;

export const PlannedValueCostElementPublicSchema = {
    properties: {
        level: {
            type: 'string',
            maxLength: 20,
            title: 'Level'
        },
        control_date: {
            type: 'string',
            format: 'date',
            title: 'Control Date'
        },
        planned_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Planned Value',
            default: '0.00'
        },
        percent_complete: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Percent Complete',
            default: '0.0000'
        },
        budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Budget Bac',
            default: '0.00'
        },
        cost_element_id: {
            type: 'string',
            format: 'uuid',
            title: 'Cost Element Id'
        }
    },
    type: 'object',
    required: ['level', 'control_date', 'cost_element_id'],
    title: 'PlannedValueCostElementPublic',
    description: 'Planned value response for cost elements.'
} as const;

export const PlannedValueProjectPublicSchema = {
    properties: {
        level: {
            type: 'string',
            maxLength: 20,
            title: 'Level'
        },
        control_date: {
            type: 'string',
            format: 'date',
            title: 'Control Date'
        },
        planned_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Planned Value',
            default: '0.00'
        },
        percent_complete: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Percent Complete',
            default: '0.0000'
        },
        budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Budget Bac',
            default: '0.00'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        }
    },
    type: 'object',
    required: ['level', 'control_date', 'project_id'],
    title: 'PlannedValueProjectPublic',
    description: 'Planned value response for projects.'
} as const;

export const PlannedValueWBEPublicSchema = {
    properties: {
        level: {
            type: 'string',
            maxLength: 20,
            title: 'Level'
        },
        control_date: {
            type: 'string',
            format: 'date',
            title: 'Control Date'
        },
        planned_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Planned Value',
            default: '0.00'
        },
        percent_complete: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Percent Complete',
            default: '0.0000'
        },
        budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Budget Bac',
            default: '0.00'
        },
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        }
    },
    type: 'object',
    required: ['level', 'control_date', 'wbe_id'],
    title: 'PlannedValueWBEPublic',
    description: 'Planned value response for WBEs.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        project_name: {
            type: 'string',
            maxLength: 200,
            title: 'Project Name'
        },
        customer_name: {
            type: 'string',
            maxLength: 200,
            title: 'Customer Name'
        },
        contract_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Contract Value',
            default: '0.00'
        },
        project_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Code'
        },
        pricelist_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pricelist Code'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        planned_completion_date: {
            type: 'string',
            format: 'date',
            title: 'Planned Completion Date'
        },
        actual_completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Completion Date'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'active'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        project_manager_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Manager Id'
        }
    },
    type: 'object',
    required: ['project_name', 'customer_name', 'start_date', 'planned_completion_date', 'project_manager_id'],
    title: 'ProjectCreate',
    description: 'Schema for creating a new project.'
} as const;

export const ProjectPublicSchema = {
    properties: {
        project_name: {
            type: 'string',
            maxLength: 200,
            title: 'Project Name'
        },
        customer_name: {
            type: 'string',
            maxLength: 200,
            title: 'Customer Name'
        },
        contract_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Contract Value',
            default: '0.00'
        },
        project_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Code'
        },
        pricelist_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pricelist Code'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        planned_completion_date: {
            type: 'string',
            format: 'date',
            title: 'Planned Completion Date'
        },
        actual_completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Completion Date'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'active'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        project_manager_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Manager Id'
        }
    },
    type: 'object',
    required: ['project_name', 'customer_name', 'start_date', 'planned_completion_date', 'project_id', 'project_manager_id'],
    title: 'ProjectPublic',
    description: 'Public project schema for API responses.'
} as const;

export const ProjectTemplateSchema = {
    properties: {
        project: {
            additionalProperties: true,
            type: 'object',
            title: 'Project'
        },
        wbes: {
            items: {
                '$ref': '#/components/schemas/WBETemplateItem'
            },
            type: 'array',
            title: 'Wbes',
            default: []
        }
    },
    type: 'object',
    required: ['project'],
    title: 'ProjectTemplate',
    description: 'Template for creating a complete project hierarchy.'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        project_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Name'
        },
        customer_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Name'
        },
        contract_value: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contract Value'
        },
        project_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Code'
        },
        pricelist_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pricelist Code'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        planned_completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Planned Completion Date'
        },
        actual_completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Completion Date'
        },
        project_manager_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Manager Id'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'ProjectUpdate',
    description: 'Schema for updating a project.'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic',
    description: 'Schema for list of projects.'
} as const;

export const TimeMachinePreferenceSchema = {
    properties: {
        time_machine_date: {
            type: 'string',
            format: 'date',
            title: 'Time Machine Date'
        }
    },
    type: 'object',
    required: ['time_machine_date'],
    title: 'TimeMachinePreference',
    description: 'Represents a resolved time machine date for the current user.'
} as const;

export const TimeMachinePreferenceUpdateSchema = {
    properties: {
        time_machine_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Machine Date'
        }
    },
    type: 'object',
    title: 'TimeMachinePreferenceUpdate',
    description: 'Payload to update or reset the stored time machine date.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'JSON payload containing access token.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: 'Schema for password update.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 200,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'controller'
        },
        department: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        time_machine_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Machine Date'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: 'Schema for creating a new user.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 200,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'controller'
        },
        department: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        time_machine_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Machine Date'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic',
    description: 'Public user schema for API responses.'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 200,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'Schema for user registration.'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['admin', 'project_manager', 'department_manager', 'controller', 'executive_viewer'],
    title: 'UserRole',
    description: 'User role enumeration.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        role: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserRole'
                },
                {
                    type: 'null'
                }
            ]
        },
        department: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        time_machine_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Machine Date'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Schema for updating a user.'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: 'Schema for updating own user profile.'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'Schema for list of users.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WBECreateSchema = {
    properties: {
        machine_type: {
            type: 'string',
            maxLength: 100,
            title: 'Machine Type'
        },
        serial_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Serial Number'
        },
        contracted_delivery_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contracted Delivery Date'
        },
        revenue_allocation: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Revenue Allocation',
            default: '0.00'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'designing'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        }
    },
    type: 'object',
    required: ['machine_type', 'project_id'],
    title: 'WBECreate',
    description: 'Schema for creating a new WBE.'
} as const;

export const WBEPublicSchema = {
    properties: {
        machine_type: {
            type: 'string',
            maxLength: 100,
            title: 'Machine Type'
        },
        serial_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Serial Number'
        },
        contracted_delivery_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contracted Delivery Date'
        },
        revenue_allocation: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Revenue Allocation',
            default: '0.00'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'designing'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        }
    },
    type: 'object',
    required: ['machine_type', 'wbe_id', 'project_id'],
    title: 'WBEPublic',
    description: 'Public WBE schema for API responses.'
} as const;

export const WBETemplateItemSchema = {
    properties: {
        wbe: {
            additionalProperties: true,
            type: 'object',
            title: 'Wbe'
        },
        cost_elements: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Cost Elements',
            default: []
        }
    },
    type: 'object',
    required: ['wbe'],
    title: 'WBETemplateItem',
    description: 'WBE with nested cost elements.'
} as const;

export const WBEUpdateSchema = {
    properties: {
        machine_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Machine Type'
        },
        serial_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Serial Number'
        },
        contracted_delivery_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contracted Delivery Date'
        },
        revenue_allocation: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Revenue Allocation'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'WBEUpdate',
    description: 'Schema for updating a WBE.'
} as const;

export const WBEWithBaselineCostElementsPublicSchema = {
    properties: {
        wbe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Wbe Id'
        },
        machine_type: {
            type: 'string',
            maxLength: 100,
            title: 'Machine Type'
        },
        serial_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Serial Number'
        },
        cost_elements: {
            items: {
                '$ref': '#/components/schemas/BaselineCostElementWithCostElementPublic'
            },
            type: 'array',
            title: 'Cost Elements'
        },
        wbe_total_budget_bac: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Wbe Total Budget Bac'
        },
        wbe_total_revenue_plan: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Wbe Total Revenue Plan'
        },
        wbe_total_planned_value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Wbe Total Planned Value'
        },
        wbe_total_actual_ac: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Wbe Total Actual Ac'
        },
        wbe_total_forecast_eac: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Wbe Total Forecast Eac'
        },
        wbe_total_earned_ev: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Wbe Total Earned Ev'
        }
    },
    type: 'object',
    required: ['wbe_id', 'machine_type', 'wbe_total_budget_bac', 'wbe_total_revenue_plan', 'wbe_total_planned_value'],
    title: 'WBEWithBaselineCostElementsPublic',
    description: 'Public WBE schema with baseline cost elements and aggregated totals.'
} as const;

export const WBEsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WBEPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WBEsPublic',
    description: 'Schema for list of WBEs.'
} as const;