// This file is auto-generated by @hey-api/openapi-ts

/**
 * Schema for creating a new app configuration.
 */
export type AppConfigurationCreate = {
    /**
     * Configuration key (e.g., 'ai_default_openai_base_url')
     */
    config_key: string;
    /**
     * Configuration value (plain text or encrypted)
     */
    config_value: string;
    /**
     * Optional description of the configuration
     */
    description?: (string | null);
    /**
     * Whether this configuration is active
     */
    is_active?: boolean;
};

/**
 * Public app configuration schema for API responses.
 */
export type AppConfigurationPublic = {
    /**
     * Configuration key (e.g., 'ai_default_openai_base_url')
     */
    config_key: string;
    /**
     * Configuration value (plain text or encrypted)
     */
    config_value: string;
    /**
     * Optional description of the configuration
     */
    description?: (string | null);
    /**
     * Whether this configuration is active
     */
    is_active?: boolean;
    config_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for list of app configurations.
 */
export type AppConfigurationsPublic = {
    data: Array<AppConfigurationPublic>;
    count: number;
};

/**
 * Schema for updating an app configuration.
 */
export type AppConfigurationUpdate = {
    config_key?: (string | null);
    config_value?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Public schema for baseline cost elements grouped by WBE.
 */
export type BaselineCostElementsByWBEPublic = {
    baseline_id: string;
    wbes?: Array<WBEWithBaselineCostElementsPublic>;
};

/**
 * Public schema for paginated list of baseline cost elements.
 */
export type BaselineCostElementsPublic = {
    data?: Array<BaselineCostElementWithCostElementPublic>;
    count?: number;
};

/**
 * Public baseline cost element schema with CostElement fields for API responses.
 */
export type BaselineCostElementWithCostElementPublic = {
    budget_bac?: string;
    revenue_plan?: string;
    actual_ac?: (string | null);
    forecast_eac?: (string | null);
    earned_ev?: (string | null);
    percent_complete?: (string | null);
    planned_value?: string;
    baseline_cost_element_id: string;
    baseline_id: string;
    cost_element_id: string;
    created_at: string;
    department_code: string;
    department_name: string;
    cost_element_type_id: string;
    wbe_id: string;
    wbe_machine_type: string;
    schedule_start_date?: (string | null);
    schedule_end_date?: (string | null);
    schedule_progression_type?: (string | null);
    schedule_registration_date?: (string | null);
    schedule_description?: (string | null);
    schedule_notes?: (string | null);
};

/**
 * Base baseline log schema with common fields.
 */
export type BaselineLogBase = {
    baseline_type: string;
    baseline_date: string;
    milestone_type: string;
    description?: (string | null);
    is_cancelled?: boolean;
    department?: (string | null);
    is_pmb?: boolean;
};

/**
 * Public baseline log schema for API responses.
 */
export type BaselineLogPublic = {
    baseline_type: string;
    baseline_date: string;
    milestone_type: string;
    description?: (string | null);
    is_cancelled?: boolean;
    department?: (string | null);
    is_pmb?: boolean;
    baseline_id: string;
    project_id: string;
    created_by_id: string;
    created_at: string;
};

/**
 * Schema for updating a baseline log entry.
 */
export type BaselineLogUpdate = {
    baseline_type?: (string | null);
    baseline_date?: (string | null);
    milestone_type?: (string | null);
    description?: (string | null);
    is_cancelled?: (boolean | null);
    department?: (string | null);
    is_pmb?: (boolean | null);
};

/**
 * Public schema for baseline summary with aggregated values.
 */
export type BaselineSummaryPublic = {
    snapshot_id: string;
    baseline_id: string;
    baseline_date: string;
    milestone_type: string;
    description?: (string | null);
    total_budget_bac: string;
    total_revenue_plan: string;
    total_planned_value: string;
    total_actual_ac?: (string | null);
    total_forecast_eac?: (string | null);
    total_earned_ev?: (string | null);
    cost_element_count?: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Public schema for budget summary response.
 */
export type BudgetSummaryPublic = {
    level: string;
    revenue_limit: string;
    total_revenue_allocated?: string;
    total_budget_bac?: string;
    total_revenue_plan?: string;
    project_id?: (string | null);
    wbe_id?: (string | null);
    calculated_at?: string;
    /**
     * Calculate remaining revenue (revenue_limit - total_revenue_allocated).
     */
    readonly remaining_revenue: string;
    /**
     * Calculate revenue utilization percentage.
     */
    readonly revenue_utilization_percent: number;
};

/**
 * Public cost categories list schema.
 */
export type CostCategoriesPublic = {
    data: Array<CostCategoryPublic>;
    count: number;
};

/**
 * Public cost category schema for API responses.
 */
export type CostCategoryPublic = {
    name: string;
    code: string;
};

/**
 * Schema for creating a new cost element.
 */
export type CostElementCreate = {
    department_code: string;
    department_name: string;
    budget_bac?: (number | string);
    revenue_plan?: (number | string);
    status?: string;
    notes?: (string | null);
    wbe_id: string;
    cost_element_type_id: string;
};

/**
 * Public cost element schema for API responses.
 */
export type CostElementPublic = {
    department_code: string;
    department_name: string;
    budget_bac?: string;
    revenue_plan?: string;
    status?: string;
    notes?: (string | null);
    cost_element_id: string;
    wbe_id: string;
    cost_element_type_id: string;
};

/**
 * Base cost element schedule schema with common fields.
 */
export type CostElementScheduleBase = {
    start_date: string;
    end_date: string;
    progression_type: string;
    registration_date?: string;
    description?: (string | null);
    notes?: (string | null);
};

/**
 * Public cost element schedule schema for API responses.
 */
export type CostElementSchedulePublic = {
    start_date: string;
    end_date: string;
    progression_type: string;
    registration_date?: string;
    description?: (string | null);
    notes?: (string | null);
    schedule_id: string;
    cost_element_id: string;
    baseline_id?: (string | null);
    created_by_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for updating a cost element schedule.
 */
export type CostElementScheduleUpdate = {
    start_date?: (string | null);
    end_date?: (string | null);
    progression_type?: (string | null);
    registration_date?: (string | null);
    description?: (string | null);
    notes?: (string | null);
};

/**
 * Schema for list of cost elements.
 */
export type CostElementsPublic = {
    data: Array<CostElementPublic>;
    count: number;
};

/**
 * Public cost element type schema for API responses.
 */
export type CostElementTypePublic = {
    type_code: string;
    type_name: string;
    category_type: string;
    tracks_hours?: boolean;
    description?: (string | null);
    display_order?: number;
    is_active?: boolean;
    cost_element_type_id: string;
    department_id?: (string | null);
    department_code?: (string | null);
    department_name?: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Schema for list of cost element types.
 */
export type CostElementTypesPublic = {
    data: Array<CostElementTypePublic>;
    count: number;
};

/**
 * Schema for updating a cost element.
 */
export type CostElementUpdate = {
    department_code?: (string | null);
    department_name?: (string | null);
    budget_bac?: (number | string | null);
    revenue_plan?: (number | string | null);
    status?: (string | null);
    notes?: (string | null);
};

/**
 * Public cost element schema with nested schedule for API responses.
 */
export type CostElementWithSchedulePublic = {
    department_code: string;
    department_name: string;
    budget_bac?: string;
    revenue_plan?: string;
    status?: string;
    notes?: (string | null);
    cost_element_id: string;
    wbe_id: string;
    cost_element_type_id: string;
    schedule?: (CostElementSchedulePublic | null);
};

/**
 * Cost Performance Report response containing all rows and project summary.
 */
export type CostPerformanceReportPublic = {
    project_id: string;
    project_name: string;
    control_date: string;
    rows?: Array<CostPerformanceReportRowPublic>;
    /**
     * Aggregated project totals (EVM metrics)
     */
    summary: EVMIndicesProjectPublic;
};

/**
 * A single row in the cost performance report representing a cost element.
 */
export type CostPerformanceReportRowPublic = {
    cost_element_id: string;
    wbe_id: string;
    /**
     * WBE machine_type
     */
    wbe_name: string;
    /**
     * WBE serial_number
     */
    wbe_serial_number?: (string | null);
    department_code: string;
    department_name: string;
    cost_element_type_id?: (string | null);
    /**
     * Cost element type name
     */
    cost_element_type_name?: (string | null);
    planned_value?: string;
    earned_value?: string;
    actual_cost?: string;
    budget_bac?: string;
    /**
     * Cost Performance Index (CPI) = EV / AC. None when AC = 0.
     */
    cpi?: (string | null);
    /**
     * Schedule Performance Index (SPI) = EV / PV. None when PV = 0.
     */
    spi?: (string | null);
    /**
     * To-Complete Performance Index (TCPI) = (BAC - EV) / (BAC - AC). Returns 'overrun' when BAC ≤ AC.
     */
    tcpi?: (string | null);
    /**
     * Cost Variance (CV) = EV - AC. Negative = over-budget, positive = under-budget, zero = on-budget.
     */
    cost_variance?: string;
    /**
     * Schedule Variance (SV) = EV - PV. Negative = behind-schedule, positive = ahead-of-schedule, zero = on-schedule.
     */
    schedule_variance?: string;
};

/**
 * Schema for creating a new cost registration.
 *
 * Note: created_by_id is set automatically by the API from current_user.
 */
export type CostRegistrationCreate = {
    registration_date: string;
    amount?: (number | string);
    cost_category: string;
    invoice_number?: (string | null);
    description: string;
    is_quality_cost?: boolean;
    cost_element_id: string;
};

/**
 * Public cost registration schema for API responses.
 */
export type CostRegistrationPublic = {
    registration_date: string;
    amount?: string;
    cost_category: string;
    invoice_number?: (string | null);
    description: string;
    is_quality_cost?: boolean;
    cost_registration_id: string;
    cost_element_id: string;
    created_by_id: string;
    created_at: string;
    last_modified_at: string;
};

/**
 * Public cost registrations list schema.
 */
export type CostRegistrationsPublic = {
    data: Array<CostRegistrationPublic>;
    count: number;
};

/**
 * Schema for updating a cost registration.
 */
export type CostRegistrationUpdate = {
    registration_date?: (string | null);
    amount?: (number | string | null);
    cost_category?: (string | null);
    invoice_number?: (string | null);
    description?: (string | null);
    is_quality_cost?: (boolean | null);
};

/**
 * Public schema for cost summary response.
 */
export type CostSummaryPublic = {
    level: string;
    total_cost?: string;
    budget_bac?: (string | null);
    cost_registration_count?: number;
    cost_element_id?: (string | null);
    wbe_id?: (string | null);
    project_id?: (string | null);
    calculated_at?: string;
    /**
     * Calculate cost percentage of budget (total_cost / budget_bac) * 100.
     */
    readonly cost_percentage_of_budget: number;
};

/**
 * Public schema for a single cost timeline point.
 */
export type CostTimelinePointPublic = {
    point_date: string;
    cumulative_cost: string;
    period_cost: string;
};

/**
 * Public schema for cost timeline response.
 */
export type CostTimelinePublic = {
    data?: Array<CostTimelinePointPublic>;
    total_cost?: string;
};

/**
 * Earned value response for cost elements.
 */
export type EarnedValueCostElementPublic = {
    level: string;
    control_date: string;
    earned_value?: string;
    percent_complete?: string;
    budget_bac?: string;
    cost_element_id: string;
};

/**
 * Public earned value entries list schema.
 */
export type EarnedValueEntriesPublic = {
    data: Array<EarnedValueEntryPublic>;
    count: number;
};

/**
 * Schema for creating a new earned value entry.
 *
 * Note: created_by_id is set automatically by the API from current_user.
 */
export type EarnedValueEntryCreate = {
    completion_date: string;
    percent_complete?: (number | string);
    earned_value?: (number | string | null);
    deliverables?: (string | null);
    description?: (string | null);
    registration_date?: string;
    cost_element_id: string;
};

/**
 * Public earned value entry schema for API responses.
 */
export type EarnedValueEntryPublic = {
    completion_date: string;
    percent_complete?: string;
    earned_value?: (string | null);
    deliverables?: (string | null);
    description?: (string | null);
    registration_date?: string;
    earned_value_id: string;
    cost_element_id: string;
    created_by_id: string;
    created_at: string;
    last_modified_at: string;
};

/**
 * Schema for updating an earned value entry.
 */
export type EarnedValueEntryUpdate = {
    completion_date?: (string | null);
    percent_complete?: (number | string | null);
    earned_value?: (number | string | null);
    deliverables?: (string | null);
    description?: (string | null);
    registration_date?: (string | null);
};

/**
 * Earned value response for projects.
 */
export type EarnedValueProjectPublic = {
    level: string;
    control_date: string;
    earned_value?: string;
    percent_complete?: string;
    budget_bac?: string;
    project_id: string;
};

/**
 * Earned value response for WBEs.
 */
export type EarnedValueWBEPublic = {
    level: string;
    control_date: string;
    earned_value?: string;
    percent_complete?: string;
    budget_bac?: string;
    wbe_id: string;
};

/**
 * EVM performance indices response for cost elements.
 */
export type EVMIndicesCostElementPublic = {
    level: string;
    control_date: string;
    /**
     * Cost Performance Index (CPI) = EV / AC. None when AC = 0.
     */
    cpi?: (string | null);
    /**
     * Schedule Performance Index (SPI) = EV / PV. None when PV = 0.
     */
    spi?: (string | null);
    /**
     * To-Complete Performance Index (TCPI) = (BAC - EV) / (BAC - AC). Returns 'overrun' when BAC ≤ AC.
     */
    tcpi?: (string | null);
    planned_value?: string;
    earned_value?: string;
    actual_cost?: string;
    budget_bac?: string;
    /**
     * Cost Variance (CV) = EV - AC. Negative = over-budget, positive = under-budget, zero = on-budget.
     */
    cost_variance?: string;
    /**
     * Schedule Variance (SV) = EV - PV. Negative = behind-schedule, positive = ahead-of-schedule, zero = on-schedule.
     */
    schedule_variance?: string;
    cost_element_id: string;
};

/**
 * EVM performance indices response for projects.
 */
export type EVMIndicesProjectPublic = {
    level: string;
    control_date: string;
    /**
     * Cost Performance Index (CPI) = EV / AC. None when AC = 0.
     */
    cpi?: (string | null);
    /**
     * Schedule Performance Index (SPI) = EV / PV. None when PV = 0.
     */
    spi?: (string | null);
    /**
     * To-Complete Performance Index (TCPI) = (BAC - EV) / (BAC - AC). Returns 'overrun' when BAC ≤ AC.
     */
    tcpi?: (string | null);
    planned_value?: string;
    earned_value?: string;
    actual_cost?: string;
    budget_bac?: string;
    /**
     * Cost Variance (CV) = EV - AC. Negative = over-budget, positive = under-budget, zero = on-budget.
     */
    cost_variance?: string;
    /**
     * Schedule Variance (SV) = EV - PV. Negative = behind-schedule, positive = ahead-of-schedule, zero = on-schedule.
     */
    schedule_variance?: string;
    project_id: string;
};

/**
 * EVM performance indices response for WBEs.
 */
export type EVMIndicesWBEPublic = {
    level: string;
    control_date: string;
    /**
     * Cost Performance Index (CPI) = EV / AC. None when AC = 0.
     */
    cpi?: (string | null);
    /**
     * Schedule Performance Index (SPI) = EV / PV. None when PV = 0.
     */
    spi?: (string | null);
    /**
     * To-Complete Performance Index (TCPI) = (BAC - EV) / (BAC - AC). Returns 'overrun' when BAC ≤ AC.
     */
    tcpi?: (string | null);
    planned_value?: string;
    earned_value?: string;
    actual_cost?: string;
    budget_bac?: string;
    /**
     * Cost Variance (CV) = EV - AC. Negative = over-budget, positive = under-budget, zero = on-budget.
     */
    cost_variance?: string;
    /**
     * Schedule Variance (SV) = EV - PV. Negative = behind-schedule, positive = ahead-of-schedule, zero = on-schedule.
     */
    schedule_variance?: string;
    wbe_id: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Generic message response.
 */
export type Message = {
    message: string;
};

/**
 * Password reset request.
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Planned value response for cost elements.
 */
export type PlannedValueCostElementPublic = {
    level: string;
    control_date: string;
    planned_value?: string;
    percent_complete?: string;
    budget_bac?: string;
    cost_element_id: string;
};

/**
 * Planned value response for projects.
 */
export type PlannedValueProjectPublic = {
    level: string;
    control_date: string;
    planned_value?: string;
    percent_complete?: string;
    budget_bac?: string;
    project_id: string;
};

/**
 * Planned value response for WBEs.
 */
export type PlannedValueWBEPublic = {
    level: string;
    control_date: string;
    planned_value?: string;
    percent_complete?: string;
    budget_bac?: string;
    wbe_id: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Schema for creating a new project.
 */
export type ProjectCreate = {
    project_name: string;
    customer_name: string;
    contract_value?: (number | string);
    project_code?: (string | null);
    pricelist_code?: (string | null);
    start_date: string;
    planned_completion_date: string;
    actual_completion_date?: (string | null);
    status?: string;
    notes?: (string | null);
    project_manager_id: string;
};

/**
 * Public project schema for API responses.
 */
export type ProjectPublic = {
    project_name: string;
    customer_name: string;
    contract_value?: string;
    project_code?: (string | null);
    pricelist_code?: (string | null);
    start_date: string;
    planned_completion_date: string;
    actual_completion_date?: (string | null);
    status?: string;
    notes?: (string | null);
    project_id: string;
    project_manager_id: string;
};

/**
 * Schema for list of projects.
 */
export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

/**
 * Template for creating a complete project hierarchy.
 */
export type ProjectTemplate = {
    project: {
        [key: string]: unknown;
    };
    wbes?: Array<WBETemplateItem>;
};

/**
 * Schema for updating a project.
 */
export type ProjectUpdate = {
    project_name?: (string | null);
    customer_name?: (string | null);
    contract_value?: (number | string | null);
    project_code?: (string | null);
    pricelist_code?: (string | null);
    start_date?: (string | null);
    planned_completion_date?: (string | null);
    actual_completion_date?: (string | null);
    project_manager_id?: (string | null);
    status?: (string | null);
    notes?: (string | null);
};

/**
 * Represents a resolved time machine date for the current user.
 */
export type TimeMachinePreference = {
    time_machine_date: string;
};

/**
 * Payload to update or reset the stored time machine date.
 */
export type TimeMachinePreferenceUpdate = {
    time_machine_date?: (string | null);
};

/**
 * JSON payload containing access token.
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Schema for password update.
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Schema for creating a new user.
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    department?: (string | null);
    full_name?: (string | null);
    time_machine_date?: (string | null);
    openai_base_url?: (string | null);
    openai_api_key_encrypted?: (string | null);
    openai_model?: (string | null);
    password: string;
};

/**
 * Public user schema for API responses.
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    department?: (string | null);
    full_name?: (string | null);
    time_machine_date?: (string | null);
    openai_base_url?: (string | null);
    openai_api_key_encrypted?: (string | null);
    openai_model?: (string | null);
    id: string;
};

/**
 * Schema for user registration.
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * User role enumeration.
 */
export type UserRole = 'admin' | 'project_manager' | 'department_manager' | 'controller' | 'executive_viewer';

/**
 * Schema for list of users.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Schema for updating a user.
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    role?: (UserRole | null);
    department?: (string | null);
    full_name?: (string | null);
    time_machine_date?: (string | null);
    openai_base_url?: (string | null);
    openai_api_key_encrypted?: (string | null);
    openai_model?: (string | null);
    password?: (string | null);
    /**
     * Plain text API key (will be encrypted)
     */
    openai_api_key?: (string | null);
};

/**
 * Schema for updating own user profile.
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    openai_base_url?: (string | null);
    /**
     * Plain text API key (will be encrypted)
     */
    openai_api_key?: (string | null);
    openai_model?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Variance Analysis Report response containing filtered rows and project summary.
 */
export type VarianceAnalysisReportPublic = {
    project_id: string;
    project_name: string;
    control_date: string;
    /**
     * Report rows (filtered to problem areas by default)
     */
    rows?: Array<VarianceAnalysisReportRowPublic>;
    /**
     * Aggregated project totals (EVM metrics)
     */
    summary: EVMIndicesProjectPublic;
    /**
     * Count of cost elements with negative CV or SV
     */
    total_problem_areas?: number;
    /**
     * Variance threshold configuration used for severity calculation
     */
    config_used?: {
        [key: string]: (string);
    };
};

/**
 * A single row in the variance analysis report representing a cost element.
 */
export type VarianceAnalysisReportRowPublic = {
    cost_element_id: string;
    wbe_id: string;
    /**
     * WBE machine_type
     */
    wbe_name: string;
    /**
     * WBE serial_number
     */
    wbe_serial_number?: (string | null);
    department_code: string;
    department_name: string;
    cost_element_type_id?: (string | null);
    /**
     * Cost element type name
     */
    cost_element_type_name?: (string | null);
    planned_value?: string;
    earned_value?: string;
    actual_cost?: string;
    budget_bac?: string;
    /**
     * Cost Performance Index (CPI) = EV / AC. None when AC = 0.
     */
    cpi?: (string | null);
    /**
     * Schedule Performance Index (SPI) = EV / PV. None when PV = 0.
     */
    spi?: (string | null);
    /**
     * To-Complete Performance Index (TCPI) = (BAC - EV) / (BAC - AC). Returns 'overrun' when BAC ≤ AC.
     */
    tcpi?: (string | null);
    /**
     * Cost Variance (CV) = EV - AC. Negative = over-budget, positive = under-budget, zero = on-budget.
     */
    cost_variance?: string;
    /**
     * Schedule Variance (SV) = EV - PV. Negative = behind-schedule, positive = ahead-of-schedule, zero = on-schedule.
     */
    schedule_variance?: string;
    /**
     * Cost Variance Percentage (CV%) = CV / BAC * 100. None when BAC = 0.
     */
    cv_percentage?: (string | null);
    /**
     * Schedule Variance Percentage (SV%) = SV / BAC * 100. None when BAC = 0.
     */
    sv_percentage?: (string | null);
    /**
     * Overall variance severity: 'critical', 'warning', or 'normal'. None if percentages undefined.
     */
    variance_severity?: (string | null);
    /**
     * True if cost variance is negative (over-budget)
     */
    has_cost_variance_issue?: boolean;
    /**
     * True if schedule variance is negative (behind-schedule)
     */
    has_schedule_variance_issue?: boolean;
};

/**
 * Schema for creating a new variance threshold configuration.
 */
export type VarianceThresholdConfigCreate = {
    threshold_type: VarianceThresholdType;
    /**
     * Threshold percentage (-100 to 0)
     */
    threshold_percentage: (number | string);
    description?: (string | null);
    is_active?: boolean;
};

/**
 * Public variance threshold configuration schema for API responses.
 */
export type VarianceThresholdConfigPublic = {
    threshold_type: VarianceThresholdType;
    /**
     * Threshold percentage (-100 to 0)
     */
    threshold_percentage: string;
    description?: (string | null);
    is_active?: boolean;
    variance_threshold_config_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for list of variance threshold configurations.
 */
export type VarianceThresholdConfigsPublic = {
    data: Array<VarianceThresholdConfigPublic>;
    count: number;
};

/**
 * Schema for updating a variance threshold configuration.
 */
export type VarianceThresholdConfigUpdate = {
    threshold_type?: (VarianceThresholdType | null);
    /**
     * Threshold percentage (-100 to 0)
     */
    threshold_percentage?: (number | string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Variance threshold type enumeration.
 */
export type VarianceThresholdType = 'critical_cv' | 'warning_cv' | 'critical_sv' | 'warning_sv';

/**
 * A single point in variance trend analysis representing a month.
 */
export type VarianceTrendPointPublic = {
    /**
     * First day of the month for this trend point
     */
    month: string;
    /**
     * Cost Variance (CV) as of end of month
     */
    cost_variance?: string;
    /**
     * Schedule Variance (SV) as of end of month
     */
    schedule_variance?: string;
    /**
     * Cost Variance Percentage (CV%) = CV / BAC * 100. None when BAC = 0.
     */
    cv_percentage?: (string | null);
    /**
     * Schedule Variance Percentage (SV%) = SV / BAC * 100. None when BAC = 0.
     */
    sv_percentage?: (string | null);
};

/**
 * Variance Trend Analysis response containing monthly variance evolution over time.
 */
export type VarianceTrendPublic = {
    project_id: string;
    /**
     * Cost element ID if cost element level, None if project/WBE level
     */
    cost_element_id?: (string | null);
    /**
     * WBE ID if WBE level, None if project level
     */
    wbe_id?: (string | null);
    /**
     * Current control date (trend ends at this date)
     */
    control_date: string;
    /**
     * Monthly variance trend points from project start to control date
     */
    trend_points?: Array<VarianceTrendPointPublic>;
};

/**
 * Schema for creating a new WBE.
 */
export type WBECreate = {
    machine_type: string;
    serial_number?: (string | null);
    contracted_delivery_date?: (string | null);
    revenue_allocation?: (number | string);
    status?: string;
    notes?: (string | null);
    project_id: string;
};

/**
 * Public WBE schema for API responses.
 */
export type WBEPublic = {
    machine_type: string;
    serial_number?: (string | null);
    contracted_delivery_date?: (string | null);
    revenue_allocation?: string;
    status?: string;
    notes?: (string | null);
    wbe_id: string;
    project_id: string;
};

/**
 * Schema for list of WBEs.
 */
export type WBEsPublic = {
    data: Array<WBEPublic>;
    count: number;
};

/**
 * WBE with nested cost elements.
 */
export type WBETemplateItem = {
    wbe: {
        [key: string]: unknown;
    };
    cost_elements?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Schema for updating a WBE.
 */
export type WBEUpdate = {
    machine_type?: (string | null);
    serial_number?: (string | null);
    contracted_delivery_date?: (string | null);
    revenue_allocation?: (number | string | null);
    status?: (string | null);
    notes?: (string | null);
};

/**
 * Public WBE schema with baseline cost elements and aggregated totals.
 */
export type WBEWithBaselineCostElementsPublic = {
    wbe_id: string;
    machine_type: string;
    serial_number?: (string | null);
    cost_elements?: Array<BaselineCostElementWithCostElementPublic>;
    wbe_total_budget_bac: string;
    wbe_total_revenue_plan: string;
    wbe_total_planned_value: string;
    wbe_total_actual_ac?: (string | null);
    wbe_total_forecast_eac?: (string | null);
    wbe_total_earned_ev?: (string | null);
};

export type AdminListAppConfigurationsResponse = (AppConfigurationsPublic);

export type AdminCreateAppConfigurationData = {
    requestBody: AppConfigurationCreate;
};

export type AdminCreateAppConfigurationResponse = (AppConfigurationPublic);

export type AdminGetAppConfigurationData = {
    configId: string;
};

export type AdminGetAppConfigurationResponse = (AppConfigurationPublic);

export type AdminUpdateAppConfigurationData = {
    configId: string;
    requestBody: AppConfigurationUpdate;
};

export type AdminUpdateAppConfigurationResponse = (AppConfigurationPublic);

export type AdminDeleteAppConfigurationData = {
    configId: string;
};

export type AdminDeleteAppConfigurationResponse = (Message);

export type AdminListVarianceThresholdConfigsResponse = (VarianceThresholdConfigsPublic);

export type AdminCreateVarianceThresholdConfigData = {
    requestBody: VarianceThresholdConfigCreate;
};

export type AdminCreateVarianceThresholdConfigResponse = (VarianceThresholdConfigPublic);

export type AdminGetVarianceThresholdConfigData = {
    configId: string;
};

export type AdminGetVarianceThresholdConfigResponse = (VarianceThresholdConfigPublic);

export type AdminUpdateVarianceThresholdConfigData = {
    configId: string;
    requestBody: VarianceThresholdConfigUpdate;
};

export type AdminUpdateVarianceThresholdConfigResponse = (VarianceThresholdConfigPublic);

export type AdminDeleteVarianceThresholdConfigData = {
    configId: string;
};

export type AdminDeleteVarianceThresholdConfigResponse = (Message);

export type BaselineLogsListBaselineLogsData = {
    /**
     * Exclude cancelled baselines
     */
    excludeCancelled?: boolean;
    projectId: string;
};

export type BaselineLogsListBaselineLogsResponse = (Array<BaselineLogPublic>);

export type BaselineLogsCreateBaselineLogData = {
    projectId: string;
    requestBody: BaselineLogBase;
};

export type BaselineLogsCreateBaselineLogResponse = (BaselineLogPublic);

export type BaselineLogsReadBaselineLogData = {
    baselineId: string;
    projectId: string;
};

export type BaselineLogsReadBaselineLogResponse = (BaselineLogPublic);

export type BaselineLogsUpdateBaselineLogData = {
    baselineId: string;
    projectId: string;
    requestBody: BaselineLogUpdate;
};

export type BaselineLogsUpdateBaselineLogResponse = (BaselineLogPublic);

export type BaselineLogsCancelBaselineLogData = {
    baselineId: string;
    projectId: string;
};

export type BaselineLogsCancelBaselineLogResponse = (BaselineLogPublic);

export type BaselineLogsGetBaselineSnapshotSummaryData = {
    baselineId: string;
    projectId: string;
};

export type BaselineLogsGetBaselineSnapshotSummaryResponse = (BaselineSummaryPublic);

export type BaselineLogsGetBaselineCostElementsByWbeData = {
    baselineId: string;
    projectId: string;
};

export type BaselineLogsGetBaselineCostElementsByWbeResponse = (BaselineCostElementsByWBEPublic);

export type BaselineLogsGetBaselineCostElementsData = {
    baselineId: string;
    limit?: number;
    projectId: string;
    skip?: number;
};

export type BaselineLogsGetBaselineCostElementsResponse = (BaselineCostElementsPublic);

export type BaselineLogsGetBaselineEarnedValueEntriesData = {
    baselineId: string;
    /**
     * Filter by cost element ID
     */
    costElementId?: (string | null);
    limit?: number;
    projectId: string;
    skip?: number;
};

export type BaselineLogsGetBaselineEarnedValueEntriesResponse = (EarnedValueEntriesPublic);

export type BudgetSummaryGetProjectBudgetSummaryData = {
    projectId: string;
};

export type BudgetSummaryGetProjectBudgetSummaryResponse = (BudgetSummaryPublic);

export type BudgetSummaryGetWbeBudgetSummaryData = {
    wbeId: string;
};

export type BudgetSummaryGetWbeBudgetSummaryResponse = (BudgetSummaryPublic);

export type BudgetTimelineGetCostElementsWithSchedulesData = {
    /**
     * Filter by cost element IDs
     */
    costElementIds?: (Array<(string)> | null);
    /**
     * Filter by cost element type IDs
     */
    costElementTypeIds?: (Array<(string)> | null);
    projectId: string;
    /**
     * Filter by WBE IDs
     */
    wbeIds?: (Array<(string)> | null);
};

export type BudgetTimelineGetCostElementsWithSchedulesResponse = (Array<CostElementWithSchedulePublic>);

export type CostCategoriesReadCostCategoriesResponse = (CostCategoriesPublic);

export type CostElementsReadCostElementsData = {
    limit?: number;
    skip?: number;
    /**
     * Filter by WBE ID
     */
    wbeId?: (string | null);
};

export type CostElementsReadCostElementsResponse = (CostElementsPublic);

export type CostElementsCreateCostElementData = {
    requestBody: CostElementCreate;
};

export type CostElementsCreateCostElementResponse = (CostElementPublic);

export type CostElementsReadCostElementData = {
    id: string;
};

export type CostElementsReadCostElementResponse = (CostElementPublic);

export type CostElementsUpdateCostElementData = {
    id: string;
    requestBody: CostElementUpdate;
};

export type CostElementsUpdateCostElementResponse = (CostElementPublic);

export type CostElementsDeleteCostElementData = {
    id: string;
};

export type CostElementsDeleteCostElementResponse = (Message);

export type CostElementSchedulesReadScheduleByCostElementData = {
    /**
     * Cost element ID
     */
    costElementId: string;
};

export type CostElementSchedulesReadScheduleByCostElementResponse = (CostElementSchedulePublic);

export type CostElementSchedulesCreateScheduleData = {
    /**
     * Cost element ID
     */
    costElementId: string;
    requestBody: CostElementScheduleBase;
};

export type CostElementSchedulesCreateScheduleResponse = (CostElementSchedulePublic);

export type CostElementSchedulesReadScheduleHistoryByCostElementData = {
    /**
     * Cost element ID
     */
    costElementId: string;
};

export type CostElementSchedulesReadScheduleHistoryByCostElementResponse = (Array<CostElementSchedulePublic>);

export type CostElementSchedulesUpdateScheduleData = {
    id: string;
    requestBody: CostElementScheduleUpdate;
};

export type CostElementSchedulesUpdateScheduleResponse = (CostElementSchedulePublic);

export type CostElementSchedulesDeleteScheduleData = {
    id: string;
};

export type CostElementSchedulesDeleteScheduleResponse = (Message);

export type CostElementTypesReadCostElementTypesResponse = (CostElementTypesPublic);

export type CostRegistrationsReadCostRegistrationsData = {
    /**
     * Filter by cost element ID
     */
    costElementId?: (string | null);
    limit?: number;
    skip?: number;
};

export type CostRegistrationsReadCostRegistrationsResponse = (CostRegistrationsPublic);

export type CostRegistrationsCreateCostRegistrationData = {
    requestBody: CostRegistrationCreate;
};

export type CostRegistrationsCreateCostRegistrationResponse = (CostRegistrationPublic);

export type CostRegistrationsReadCostRegistrationData = {
    id: string;
};

export type CostRegistrationsReadCostRegistrationResponse = (CostRegistrationPublic);

export type CostRegistrationsUpdateCostRegistrationData = {
    id: string;
    requestBody: CostRegistrationUpdate;
};

export type CostRegistrationsUpdateCostRegistrationResponse = (CostRegistrationPublic);

export type CostRegistrationsDeleteCostRegistrationData = {
    id: string;
};

export type CostRegistrationsDeleteCostRegistrationResponse = (Message);

export type CostSummaryGetCostElementCostSummaryData = {
    costElementId: string;
    /**
     * Filter by quality cost
     */
    isQualityCost?: (boolean | null);
};

export type CostSummaryGetCostElementCostSummaryResponse = (CostSummaryPublic);

export type CostSummaryGetWbeCostSummaryData = {
    /**
     * Filter by quality cost
     */
    isQualityCost?: (boolean | null);
    wbeId: string;
};

export type CostSummaryGetWbeCostSummaryResponse = (CostSummaryPublic);

export type CostSummaryGetProjectCostSummaryData = {
    /**
     * Filter by quality cost
     */
    isQualityCost?: (boolean | null);
    projectId: string;
};

export type CostSummaryGetProjectCostSummaryResponse = (CostSummaryPublic);

export type CostTimelineGetProjectCostTimelineData = {
    /**
     * Filter by cost element IDs
     */
    costElementIds?: (Array<(string)> | null);
    /**
     * End date for time series
     */
    endDate?: (string | null);
    projectId: string;
    /**
     * Start date for time series
     */
    startDate?: (string | null);
    /**
     * Filter by WBE IDs
     */
    wbeIds?: (Array<(string)> | null);
};

export type CostTimelineGetProjectCostTimelineResponse = (CostTimelinePublic);

export type EarnedValueGetCostElementEarnedValueData = {
    costElementId: string;
    projectId: string;
};

export type EarnedValueGetCostElementEarnedValueResponse = (EarnedValueCostElementPublic);

export type EarnedValueGetWbeEarnedValueData = {
    projectId: string;
    wbeId: string;
};

export type EarnedValueGetWbeEarnedValueResponse = (EarnedValueWBEPublic);

export type EarnedValueGetProjectEarnedValueData = {
    projectId: string;
};

export type EarnedValueGetProjectEarnedValueResponse = (EarnedValueProjectPublic);

export type EarnedValueEntriesReadEarnedValueEntriesData = {
    /**
     * Filter by cost element ID
     */
    costElementId?: (string | null);
    limit?: number;
    skip?: number;
};

export type EarnedValueEntriesReadEarnedValueEntriesResponse = (EarnedValueEntriesPublic);

export type EarnedValueEntriesCreateEarnedValueEntryData = {
    requestBody: EarnedValueEntryCreate;
};

export type EarnedValueEntriesCreateEarnedValueEntryResponse = (EarnedValueEntryPublic);

export type EarnedValueEntriesReadEarnedValueEntryData = {
    earnedValueId: string;
};

export type EarnedValueEntriesReadEarnedValueEntryResponse = (EarnedValueEntryPublic);

export type EarnedValueEntriesUpdateEarnedValueEntryData = {
    earnedValueId: string;
    requestBody: EarnedValueEntryUpdate;
};

export type EarnedValueEntriesUpdateEarnedValueEntryResponse = (EarnedValueEntryPublic);

export type EarnedValueEntriesDeleteEarnedValueEntryData = {
    earnedValueId: string;
};

export type EarnedValueEntriesDeleteEarnedValueEntryResponse = (Message);

export type EvmIndicesGetWbeEvmIndicesData = {
    projectId: string;
    wbeId: string;
};

export type EvmIndicesGetWbeEvmIndicesResponse = (EVMIndicesWBEPublic);

export type EvmIndicesGetProjectEvmIndicesData = {
    projectId: string;
};

export type EvmIndicesGetProjectEvmIndicesResponse = (EVMIndicesProjectPublic);

export type EvmMetricsGetCostElementEvmMetricsEndpointData = {
    costElementId: string;
    projectId: string;
};

export type EvmMetricsGetCostElementEvmMetricsEndpointResponse = (EVMIndicesCostElementPublic);

export type EvmMetricsGetWbeEvmMetricsEndpointData = {
    projectId: string;
    wbeId: string;
};

export type EvmMetricsGetWbeEvmMetricsEndpointResponse = (EVMIndicesWBEPublic);

export type EvmMetricsGetProjectEvmMetricsEndpointData = {
    projectId: string;
};

export type EvmMetricsGetProjectEvmMetricsEndpointResponse = (EVMIndicesProjectPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PlannedValueGetCostElementPlannedValueData = {
    /**
     * Control date for planned value
     */
    controlDate: string;
    costElementId: string;
    projectId: string;
};

export type PlannedValueGetCostElementPlannedValueResponse = (PlannedValueCostElementPublic);

export type PlannedValueGetWbePlannedValueData = {
    /**
     * Control date for planned value
     */
    controlDate: string;
    projectId: string;
    wbeId: string;
};

export type PlannedValueGetWbePlannedValueResponse = (PlannedValueWBEPublic);

export type PlannedValueGetProjectPlannedValueData = {
    /**
     * Control date for planned value
     */
    controlDate: string;
    projectId: string;
};

export type PlannedValueGetProjectPlannedValueResponse = (PlannedValueProjectPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadProjectData = {
    id: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    id: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    id: string;
};

export type ProjectsDeleteProjectResponse = (Message);

export type ProjectsCreateProjectFromTemplateData = {
    requestBody: ProjectTemplate;
};

export type ProjectsCreateProjectFromTemplateResponse = (ProjectPublic);

export type ReportsGetProjectCostPerformanceReportEndpointData = {
    projectId: string;
};

export type ReportsGetProjectCostPerformanceReportEndpointResponse = (CostPerformanceReportPublic);

export type ReportsGetProjectVarianceAnalysisReportEndpointData = {
    projectId: string;
    /**
     * Filter to show only problem areas (negative CV or SV)
     */
    showOnlyProblems?: boolean;
    /**
     * Sort field: 'cv' (cost variance) or 'sv' (schedule variance)
     */
    sortBy?: string;
};

export type ReportsGetProjectVarianceAnalysisReportEndpointResponse = (VarianceAnalysisReportPublic);

export type ReportsGetVarianceTrendEndpointData = {
    /**
     * Optional cost element ID for cost element-level trend (cannot be used with wbe_id)
     */
    costElementId?: (string | null);
    projectId: string;
    /**
     * Optional WBE ID for WBE-level trend
     */
    wbeId?: (string | null);
};

export type ReportsGetVarianceTrendEndpointResponse = (VarianceTrendPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadTimeMachinePreferenceResponse = (TimeMachinePreference);

export type UsersUpdateTimeMachinePreferenceData = {
    requestBody: TimeMachinePreferenceUpdate;
};

export type UsersUpdateTimeMachinePreferenceResponse = (TimeMachinePreference);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WbesReadWbesData = {
    limit?: number;
    /**
     * Filter by project ID
     */
    projectId?: (string | null);
    skip?: number;
};

export type WbesReadWbesResponse = (WBEsPublic);

export type WbesCreateWbeData = {
    requestBody: WBECreate;
};

export type WbesCreateWbeResponse = (WBEPublic);

export type WbesReadWbeData = {
    id: string;
};

export type WbesReadWbeResponse = (WBEPublic);

export type WbesUpdateWbeData = {
    id: string;
    requestBody: WBEUpdate;
};

export type WbesUpdateWbeResponse = (WBEPublic);

export type WbesDeleteWbeData = {
    id: string;
};

export type WbesDeleteWbeResponse = (Message);