// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Public schema for budget summary response.
 */
export type BudgetSummaryPublic = {
    level: string;
    revenue_limit: string;
    total_revenue_allocated?: string;
    total_budget_bac?: string;
    total_revenue_plan?: string;
    project_id?: (string | null);
    wbe_id?: (string | null);
    calculated_at?: string;
    /**
     * Calculate remaining revenue (revenue_limit - total_revenue_allocated).
     */
    readonly remaining_revenue: string;
    /**
     * Calculate revenue utilization percentage.
     */
    readonly revenue_utilization_percent: number;
};

/**
 * Schema for creating a new cost element.
 */
export type CostElementCreate = {
    department_code: string;
    department_name: string;
    budget_bac?: (number | string);
    revenue_plan?: (number | string);
    status?: string;
    notes?: (string | null);
    wbe_id: string;
    cost_element_type_id: string;
};

/**
 * Public cost element schema for API responses.
 */
export type CostElementPublic = {
    department_code: string;
    department_name: string;
    budget_bac?: string;
    revenue_plan?: string;
    status?: string;
    notes?: (string | null);
    cost_element_id: string;
    wbe_id: string;
    cost_element_type_id: string;
};

/**
 * Base cost element schedule schema with common fields.
 */
export type CostElementScheduleBase = {
    start_date: string;
    end_date: string;
    progression_type: string;
    notes?: (string | null);
};

/**
 * Public cost element schedule schema for API responses.
 */
export type CostElementSchedulePublic = {
    start_date: string;
    end_date: string;
    progression_type: string;
    notes?: (string | null);
    schedule_id: string;
    cost_element_id: string;
    baseline_id?: (string | null);
    created_by_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for updating a cost element schedule.
 */
export type CostElementScheduleUpdate = {
    start_date?: (string | null);
    end_date?: (string | null);
    progression_type?: (string | null);
    notes?: (string | null);
};

/**
 * Schema for list of cost elements.
 */
export type CostElementsPublic = {
    data: Array<CostElementPublic>;
    count: number;
};

/**
 * Public cost element type schema for API responses.
 */
export type CostElementTypePublic = {
    type_code: string;
    type_name: string;
    category_type: string;
    tracks_hours?: boolean;
    description?: (string | null);
    display_order?: number;
    is_active?: boolean;
    cost_element_type_id: string;
    department_id?: (string | null);
    department_code?: (string | null);
    department_name?: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Schema for list of cost element types.
 */
export type CostElementTypesPublic = {
    data: Array<CostElementTypePublic>;
    count: number;
};

/**
 * Schema for updating a cost element.
 */
export type CostElementUpdate = {
    department_code?: (string | null);
    department_name?: (string | null);
    budget_bac?: (number | string | null);
    revenue_plan?: (number | string | null);
    status?: (string | null);
    notes?: (string | null);
};

/**
 * Public cost element schema with nested schedule for API responses.
 */
export type CostElementWithSchedulePublic = {
    department_code: string;
    department_name: string;
    budget_bac?: string;
    revenue_plan?: string;
    status?: string;
    notes?: (string | null);
    cost_element_id: string;
    wbe_id: string;
    cost_element_type_id: string;
    schedule?: (CostElementSchedulePublic | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Generic message response.
 */
export type Message = {
    message: string;
};

/**
 * Password reset request.
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Schema for creating a new project.
 */
export type ProjectCreate = {
    project_name: string;
    customer_name: string;
    contract_value?: (number | string);
    project_code?: (string | null);
    pricelist_code?: (string | null);
    start_date: string;
    planned_completion_date: string;
    actual_completion_date?: (string | null);
    status?: string;
    notes?: (string | null);
    project_manager_id: string;
};

/**
 * Public project schema for API responses.
 */
export type ProjectPublic = {
    project_name: string;
    customer_name: string;
    contract_value?: string;
    project_code?: (string | null);
    pricelist_code?: (string | null);
    start_date: string;
    planned_completion_date: string;
    actual_completion_date?: (string | null);
    status?: string;
    notes?: (string | null);
    project_id: string;
    project_manager_id: string;
};

/**
 * Schema for list of projects.
 */
export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

/**
 * Template for creating a complete project hierarchy.
 */
export type ProjectTemplate = {
    project: {
        [key: string]: unknown;
    };
    wbes?: Array<WBETemplateItem>;
};

/**
 * Schema for updating a project.
 */
export type ProjectUpdate = {
    project_name?: (string | null);
    customer_name?: (string | null);
    contract_value?: (number | string | null);
    project_code?: (string | null);
    pricelist_code?: (string | null);
    start_date?: (string | null);
    planned_completion_date?: (string | null);
    actual_completion_date?: (string | null);
    project_manager_id?: (string | null);
    status?: (string | null);
    notes?: (string | null);
};

/**
 * JSON payload containing access token.
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Schema for password update.
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Schema for creating a new user.
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    department?: (string | null);
    full_name?: (string | null);
    password: string;
};

/**
 * Public user schema for API responses.
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    role?: UserRole;
    department?: (string | null);
    full_name?: (string | null);
    id: string;
};

/**
 * Schema for user registration.
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * User role enumeration.
 */
export type UserRole = 'admin' | 'project_manager' | 'department_manager' | 'controller' | 'executive_viewer';

/**
 * Schema for list of users.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Schema for updating a user.
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    role?: (UserRole | null);
    department?: (string | null);
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * Schema for updating own user profile.
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Schema for creating a new WBE.
 */
export type WBECreate = {
    machine_type: string;
    serial_number?: (string | null);
    contracted_delivery_date?: (string | null);
    revenue_allocation?: (number | string);
    status?: string;
    notes?: (string | null);
    project_id: string;
};

/**
 * Public WBE schema for API responses.
 */
export type WBEPublic = {
    machine_type: string;
    serial_number?: (string | null);
    contracted_delivery_date?: (string | null);
    revenue_allocation?: string;
    status?: string;
    notes?: (string | null);
    wbe_id: string;
    project_id: string;
};

/**
 * Schema for list of WBEs.
 */
export type WBEsPublic = {
    data: Array<WBEPublic>;
    count: number;
};

/**
 * WBE with nested cost elements.
 */
export type WBETemplateItem = {
    wbe: {
        [key: string]: unknown;
    };
    cost_elements?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * Schema for updating a WBE.
 */
export type WBEUpdate = {
    machine_type?: (string | null);
    serial_number?: (string | null);
    contracted_delivery_date?: (string | null);
    revenue_allocation?: (number | string | null);
    status?: (string | null);
    notes?: (string | null);
};

export type BudgetSummaryGetProjectBudgetSummaryData = {
    projectId: string;
};

export type BudgetSummaryGetProjectBudgetSummaryResponse = (BudgetSummaryPublic);

export type BudgetSummaryGetWbeBudgetSummaryData = {
    wbeId: string;
};

export type BudgetSummaryGetWbeBudgetSummaryResponse = (BudgetSummaryPublic);

export type BudgetTimelineGetCostElementsWithSchedulesData = {
    /**
     * Filter by cost element IDs
     */
    costElementIds?: (Array<(string)> | null);
    /**
     * Filter by cost element type IDs
     */
    costElementTypeIds?: (Array<(string)> | null);
    projectId: string;
    /**
     * Filter by WBE IDs
     */
    wbeIds?: (Array<(string)> | null);
};

export type BudgetTimelineGetCostElementsWithSchedulesResponse = (Array<CostElementWithSchedulePublic>);

export type CostElementsReadCostElementsData = {
    limit?: number;
    skip?: number;
    /**
     * Filter by WBE ID
     */
    wbeId?: (string | null);
};

export type CostElementsReadCostElementsResponse = (CostElementsPublic);

export type CostElementsCreateCostElementData = {
    requestBody: CostElementCreate;
};

export type CostElementsCreateCostElementResponse = (CostElementPublic);

export type CostElementsReadCostElementData = {
    id: string;
};

export type CostElementsReadCostElementResponse = (CostElementPublic);

export type CostElementsUpdateCostElementData = {
    id: string;
    requestBody: CostElementUpdate;
};

export type CostElementsUpdateCostElementResponse = (CostElementPublic);

export type CostElementsDeleteCostElementData = {
    id: string;
};

export type CostElementsDeleteCostElementResponse = (Message);

export type CostElementSchedulesReadScheduleByCostElementData = {
    /**
     * Cost element ID
     */
    costElementId: string;
};

export type CostElementSchedulesReadScheduleByCostElementResponse = (CostElementSchedulePublic);

export type CostElementSchedulesCreateScheduleData = {
    /**
     * Cost element ID
     */
    costElementId: string;
    requestBody: CostElementScheduleBase;
};

export type CostElementSchedulesCreateScheduleResponse = (CostElementSchedulePublic);

export type CostElementSchedulesUpdateScheduleData = {
    id: string;
    requestBody: CostElementScheduleUpdate;
};

export type CostElementSchedulesUpdateScheduleResponse = (CostElementSchedulePublic);

export type CostElementSchedulesDeleteScheduleData = {
    id: string;
};

export type CostElementSchedulesDeleteScheduleResponse = (Message);

export type CostElementTypesReadCostElementTypesResponse = (CostElementTypesPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadProjectData = {
    id: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    id: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    id: string;
};

export type ProjectsDeleteProjectResponse = (Message);

export type ProjectsCreateProjectFromTemplateData = {
    requestBody: ProjectTemplate;
};

export type ProjectsCreateProjectFromTemplateResponse = (ProjectPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WbesReadWbesData = {
    limit?: number;
    /**
     * Filter by project ID
     */
    projectId?: (string | null);
    skip?: number;
};

export type WbesReadWbesResponse = (WBEsPublic);

export type WbesCreateWbeData = {
    requestBody: WBECreate;
};

export type WbesCreateWbeResponse = (WBEPublic);

export type WbesReadWbeData = {
    id: string;
};

export type WbesReadWbeResponse = (WBEPublic);

export type WbesUpdateWbeData = {
    id: string;
    requestBody: WBEUpdate;
};

export type WbesUpdateWbeResponse = (WBEPublic);

export type WbesDeleteWbeData = {
    id: string;
};

export type WbesDeleteWbeResponse = (Message);