import {
  Button,
  DialogActionTrigger,
  DialogTitle,
  Input,
  Text,
  Textarea,
  VStack,
} from "@chakra-ui/react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { useEffect, useState } from "react"
import { Controller, type SubmitHandler, useForm } from "react-hook-form"
import { FaPlus } from "react-icons/fa"
import {
  type ChangeOrderCreate,
  ChangeOrdersService,
  UsersService,
} from "@/client"
import type { ApiError } from "@/client/core/ApiError"
import useCustomToast from "@/hooks/useCustomToast"
import { handleError } from "@/utils"
import {
  DialogBody,
  DialogCloseTrigger,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogRoot,
  DialogTrigger,
} from "../ui/dialog"
import { Field } from "../ui/field"

interface AddChangeOrderProps {
  projectId: string
}

const AddChangeOrder = ({ projectId }: AddChangeOrderProps) => {
  const [isOpen, setIsOpen] = useState(false)
  const queryClient = useQueryClient()
  const { showSuccessToast, showErrorToast } = useCustomToast()

  // Get current user for created_by_id
  const { data: currentUser } = useQuery({
    queryFn: () => UsersService.readUserMe(),
    queryKey: ["users", "me"],
  })

  const {
    control,
    register,
    handleSubmit,
    reset,
    formState: { errors, isValid, isSubmitting },
  } = useForm<ChangeOrderCreate>({
    mode: "onBlur",
    criteriaMode: "all",
    defaultValues: {
      title: "",
      description: "",
      requesting_party: "",
      justification: null,
      effective_date: new Date().toISOString().split("T")[0],
      cost_impact: null,
      revenue_impact: null,
      workflow_status: "design",
      project_id: projectId,
      created_by_id: currentUser?.id || "",
      change_order_number: null, // Auto-generated by backend
    },
  })

  // Update created_by_id when currentUser loads
  useEffect(() => {
    if (currentUser?.id) {
      reset((prev) => ({
        ...prev,
        created_by_id: currentUser.id,
      }))
    }
  }, [currentUser?.id, reset])

  const mutation = useMutation({
    mutationFn: (data: ChangeOrderCreate) =>
      ChangeOrdersService.createChangeOrder({
        projectId,
        requestBody: data,
      }),
    onSuccess: () => {
      showSuccessToast("Change Order created successfully.")
      reset()
      setIsOpen(false)
    },
    onError: (err: ApiError) => {
      handleError(err)
    },
    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: ["change-orders"] })
    },
  })

  const onSubmit: SubmitHandler<ChangeOrderCreate> = (data) => {
    if (!currentUser?.id) {
      showErrorToast("Please wait for user information to load.")
      return
    }
    mutation.mutate({
      ...data,
      created_by_id: currentUser.id,
      project_id: projectId,
    })
  }

  return (
    <DialogRoot
      size={{ base: "xs", md: "lg" }}
      placement="center"
      open={isOpen}
      onOpenChange={({ open }) => setIsOpen(open)}
    >
      <DialogTrigger asChild>
        <Button value="add-change-order" my={4}>
          <FaPlus fontSize="16px" />
          Add Change Order
        </Button>
      </DialogTrigger>
      <DialogContent>
        <form onSubmit={handleSubmit(onSubmit)}>
          <DialogHeader>
            <DialogTitle>Add Change Order</DialogTitle>
          </DialogHeader>
          <DialogBody>
            <Text mb={4}>
              Fill in the form below to create a new change order. A branch will
              be created automatically.
            </Text>
            <VStack gap={4}>
              <Field
                required
                invalid={!!errors.title}
                errorText={errors.title?.message}
                label="Title"
              >
                <Input
                  {...register("title", {
                    required: "Title is required",
                  })}
                  placeholder="Change Order Title"
                  type="text"
                />
              </Field>

              <Field
                required
                invalid={!!errors.description}
                errorText={errors.description?.message}
                label="Description"
              >
                <Textarea
                  {...register("description", {
                    required: "Description is required",
                  })}
                  placeholder="Change Order Description"
                  rows={4}
                />
              </Field>

              <Field
                required
                invalid={!!errors.requesting_party}
                errorText={errors.requesting_party?.message}
                label="Requesting Party"
              >
                <Input
                  {...register("requesting_party", {
                    required: "Requesting party is required",
                  })}
                  placeholder="Requesting Party"
                  type="text"
                />
              </Field>

              <Field
                invalid={!!errors.justification}
                errorText={errors.justification?.message}
                label="Justification"
              >
                <Textarea
                  {...register("justification")}
                  placeholder="Justification (optional)"
                  rows={3}
                />
              </Field>

              <Field
                required
                invalid={!!errors.effective_date}
                errorText={errors.effective_date?.message}
                label="Effective Date"
              >
                <Input
                  {...register("effective_date", {
                    required: "Effective date is required",
                  })}
                  type="date"
                />
              </Field>

              <Field
                invalid={!!errors.cost_impact}
                errorText={errors.cost_impact?.message}
                label="Cost Impact"
              >
                <Input
                  {...register("cost_impact", {
                    min: {
                      value: 0,
                      message: "Cost impact must be positive",
                    },
                  })}
                  placeholder="0.00"
                  type="number"
                  step="0.01"
                />
              </Field>

              <Field
                invalid={!!errors.revenue_impact}
                errorText={errors.revenue_impact?.message}
                label="Revenue Impact"
              >
                <Input
                  {...register("revenue_impact", {
                    min: {
                      value: 0,
                      message: "Revenue impact must be positive",
                    },
                  })}
                  placeholder="0.00"
                  type="number"
                  step="0.01"
                />
              </Field>

              <Field
                required
                invalid={!!errors.workflow_status}
                errorText={errors.workflow_status?.message}
                label="Workflow Status"
              >
                <Controller
                  control={control}
                  name="workflow_status"
                  rules={{ required: "Workflow status is required" }}
                  render={({ field }) => (
                    <select
                      {...field}
                      style={{
                        width: "100%",
                        padding: "8px",
                        borderRadius: "4px",
                        border: errors.workflow_status
                          ? "1px solid #ef4444"
                          : "1px solid #e2e8f0",
                      }}
                    >
                      <option value="design">Design</option>
                      <option value="approve">Approve</option>
                      <option value="execute">Execute</option>
                    </select>
                  )}
                />
              </Field>
            </VStack>
          </DialogBody>

          <DialogFooter gap={2}>
            <DialogActionTrigger asChild>
              <Button
                variant="subtle"
                colorPalette="gray"
                disabled={isSubmitting}
              >
                Cancel
              </Button>
            </DialogActionTrigger>
            <Button
              variant="solid"
              type="submit"
              disabled={!isValid || isSubmitting || !currentUser?.id}
              loading={isSubmitting}
            >
              Save
            </Button>
          </DialogFooter>
        </form>
        <DialogCloseTrigger />
      </DialogContent>
    </DialogRoot>
  )
}

export default AddChangeOrder
