"""add_department_and_is_pmb_to_baseline_log

Revision ID: f3875ccda499
Revises: 6a75fe3eeb49
Create Date: 2025-11-06 07:42:57.125846

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f3875ccda499'
down_revision = '6a75fe3eeb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add department column (nullable, VARCHAR(100))
    op.add_column('baselinelog', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))

    # Add is_pmb column (Boolean, default=False)
    op.add_column('baselinelog', sa.Column('is_pmb', sa.Boolean(), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE baselinelog SET is_pmb = false WHERE is_pmb IS NULL")

    # Migrate data from BaselineSnapshot to BaselineLog
    # Copy department and is_pmb values from BaselineSnapshot to BaselineLog
    # based on the one-to-one relationship via baseline_id
    op.execute("""
        UPDATE baselinelog bl
        SET department = bs.department,
            is_pmb = bs.is_pmb
        FROM baselinesnapshot bs
        WHERE bl.baseline_id = bs.baseline_id
    """)

    # Make is_pmb NOT NULL with default after data migration
    op.alter_column('baselinelog', 'is_pmb', nullable=False, server_default='false')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop columns
    op.drop_column('baselinelog', 'is_pmb')
    op.drop_column('baselinelog', 'department')
    # ### end Alembic commands ###
