/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProjectsIdRouteImport } from './routes/_layout/projects.$id'
import { Route as LayoutProjectsIdBudgetTimelineRouteImport } from './routes/_layout/projects.$id.budget-timeline'
import { Route as LayoutProjectsIdWbesWbeIdRouteImport } from './routes/_layout/projects.$id.wbes.$wbeId'
import { Route as LayoutProjectsIdReportsVarianceAnalysisRouteImport } from './routes/_layout/projects.$id.reports.variance-analysis'
import { Route as LayoutProjectsIdReportsProjectPerformanceDashboardRouteImport } from './routes/_layout/projects.$id.reports.project-performance-dashboard'
import { Route as LayoutProjectsIdReportsCostPerformanceRouteImport } from './routes/_layout/projects.$id.reports.cost-performance'
import { Route as LayoutProjectsIdBaselinesBaselineIdRouteImport } from './routes/_layout/projects.$id.baselines.$baselineId'
import { Route as LayoutProjectsIdWbesWbeIdCostElementsCostElementIdRouteImport } from './routes/_layout/projects.$id.wbes.$wbeId.cost-elements.$costElementId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIdRoute = LayoutProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const LayoutProjectsIdBudgetTimelineRoute =
  LayoutProjectsIdBudgetTimelineRouteImport.update({
    id: '/budget-timeline',
    path: '/budget-timeline',
    getParentRoute: () => LayoutProjectsIdRoute,
  } as any)
const LayoutProjectsIdWbesWbeIdRoute =
  LayoutProjectsIdWbesWbeIdRouteImport.update({
    id: '/wbes/$wbeId',
    path: '/wbes/$wbeId',
    getParentRoute: () => LayoutProjectsIdRoute,
  } as any)
const LayoutProjectsIdReportsVarianceAnalysisRoute =
  LayoutProjectsIdReportsVarianceAnalysisRouteImport.update({
    id: '/reports/variance-analysis',
    path: '/reports/variance-analysis',
    getParentRoute: () => LayoutProjectsIdRoute,
  } as any)
const LayoutProjectsIdReportsProjectPerformanceDashboardRoute =
  LayoutProjectsIdReportsProjectPerformanceDashboardRouteImport.update({
    id: '/reports/project-performance-dashboard',
    path: '/reports/project-performance-dashboard',
    getParentRoute: () => LayoutProjectsIdRoute,
  } as any)
const LayoutProjectsIdReportsCostPerformanceRoute =
  LayoutProjectsIdReportsCostPerformanceRouteImport.update({
    id: '/reports/cost-performance',
    path: '/reports/cost-performance',
    getParentRoute: () => LayoutProjectsIdRoute,
  } as any)
const LayoutProjectsIdBaselinesBaselineIdRoute =
  LayoutProjectsIdBaselinesBaselineIdRouteImport.update({
    id: '/baselines/$baselineId',
    path: '/baselines/$baselineId',
    getParentRoute: () => LayoutProjectsIdRoute,
  } as any)
const LayoutProjectsIdWbesWbeIdCostElementsCostElementIdRoute =
  LayoutProjectsIdWbesWbeIdCostElementsCostElementIdRouteImport.update({
    id: '/cost-elements/$costElementId',
    path: '/cost-elements/$costElementId',
    getParentRoute: () => LayoutProjectsIdWbesWbeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/projects/$id': typeof LayoutProjectsIdRouteWithChildren
  '/projects/$id/budget-timeline': typeof LayoutProjectsIdBudgetTimelineRoute
  '/projects/$id/baselines/$baselineId': typeof LayoutProjectsIdBaselinesBaselineIdRoute
  '/projects/$id/reports/cost-performance': typeof LayoutProjectsIdReportsCostPerformanceRoute
  '/projects/$id/reports/project-performance-dashboard': typeof LayoutProjectsIdReportsProjectPerformanceDashboardRoute
  '/projects/$id/reports/variance-analysis': typeof LayoutProjectsIdReportsVarianceAnalysisRoute
  '/projects/$id/wbes/$wbeId': typeof LayoutProjectsIdWbesWbeIdRouteWithChildren
  '/projects/$id/wbes/$wbeId/cost-elements/$costElementId': typeof LayoutProjectsIdWbesWbeIdCostElementsCostElementIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/projects/$id': typeof LayoutProjectsIdRouteWithChildren
  '/projects/$id/budget-timeline': typeof LayoutProjectsIdBudgetTimelineRoute
  '/projects/$id/baselines/$baselineId': typeof LayoutProjectsIdBaselinesBaselineIdRoute
  '/projects/$id/reports/cost-performance': typeof LayoutProjectsIdReportsCostPerformanceRoute
  '/projects/$id/reports/project-performance-dashboard': typeof LayoutProjectsIdReportsProjectPerformanceDashboardRoute
  '/projects/$id/reports/variance-analysis': typeof LayoutProjectsIdReportsVarianceAnalysisRoute
  '/projects/$id/wbes/$wbeId': typeof LayoutProjectsIdWbesWbeIdRouteWithChildren
  '/projects/$id/wbes/$wbeId/cost-elements/$costElementId': typeof LayoutProjectsIdWbesWbeIdCostElementsCostElementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/projects': typeof LayoutProjectsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/projects/$id': typeof LayoutProjectsIdRouteWithChildren
  '/_layout/projects/$id/budget-timeline': typeof LayoutProjectsIdBudgetTimelineRoute
  '/_layout/projects/$id/baselines/$baselineId': typeof LayoutProjectsIdBaselinesBaselineIdRoute
  '/_layout/projects/$id/reports/cost-performance': typeof LayoutProjectsIdReportsCostPerformanceRoute
  '/_layout/projects/$id/reports/project-performance-dashboard': typeof LayoutProjectsIdReportsProjectPerformanceDashboardRoute
  '/_layout/projects/$id/reports/variance-analysis': typeof LayoutProjectsIdReportsVarianceAnalysisRoute
  '/_layout/projects/$id/wbes/$wbeId': typeof LayoutProjectsIdWbesWbeIdRouteWithChildren
  '/_layout/projects/$id/wbes/$wbeId/cost-elements/$costElementId': typeof LayoutProjectsIdWbesWbeIdCostElementsCostElementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/projects'
    | '/settings'
    | '/'
    | '/projects/$id'
    | '/projects/$id/budget-timeline'
    | '/projects/$id/baselines/$baselineId'
    | '/projects/$id/reports/cost-performance'
    | '/projects/$id/reports/project-performance-dashboard'
    | '/projects/$id/reports/variance-analysis'
    | '/projects/$id/wbes/$wbeId'
    | '/projects/$id/wbes/$wbeId/cost-elements/$costElementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/projects'
    | '/settings'
    | '/'
    | '/projects/$id'
    | '/projects/$id/budget-timeline'
    | '/projects/$id/baselines/$baselineId'
    | '/projects/$id/reports/cost-performance'
    | '/projects/$id/reports/project-performance-dashboard'
    | '/projects/$id/reports/variance-analysis'
    | '/projects/$id/wbes/$wbeId'
    | '/projects/$id/wbes/$wbeId/cost-elements/$costElementId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/projects'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/projects/$id'
    | '/_layout/projects/$id/budget-timeline'
    | '/_layout/projects/$id/baselines/$baselineId'
    | '/_layout/projects/$id/reports/cost-performance'
    | '/_layout/projects/$id/reports/project-performance-dashboard'
    | '/_layout/projects/$id/reports/variance-analysis'
    | '/_layout/projects/$id/wbes/$wbeId'
    | '/_layout/projects/$id/wbes/$wbeId/cost-elements/$costElementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$id': {
      id: '/_layout/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof LayoutProjectsIdRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/_layout/projects/$id/budget-timeline': {
      id: '/_layout/projects/$id/budget-timeline'
      path: '/budget-timeline'
      fullPath: '/projects/$id/budget-timeline'
      preLoaderRoute: typeof LayoutProjectsIdBudgetTimelineRouteImport
      parentRoute: typeof LayoutProjectsIdRoute
    }
    '/_layout/projects/$id/wbes/$wbeId': {
      id: '/_layout/projects/$id/wbes/$wbeId'
      path: '/wbes/$wbeId'
      fullPath: '/projects/$id/wbes/$wbeId'
      preLoaderRoute: typeof LayoutProjectsIdWbesWbeIdRouteImport
      parentRoute: typeof LayoutProjectsIdRoute
    }
    '/_layout/projects/$id/reports/variance-analysis': {
      id: '/_layout/projects/$id/reports/variance-analysis'
      path: '/reports/variance-analysis'
      fullPath: '/projects/$id/reports/variance-analysis'
      preLoaderRoute: typeof LayoutProjectsIdReportsVarianceAnalysisRouteImport
      parentRoute: typeof LayoutProjectsIdRoute
    }
    '/_layout/projects/$id/reports/project-performance-dashboard': {
      id: '/_layout/projects/$id/reports/project-performance-dashboard'
      path: '/reports/project-performance-dashboard'
      fullPath: '/projects/$id/reports/project-performance-dashboard'
      preLoaderRoute: typeof LayoutProjectsIdReportsProjectPerformanceDashboardRouteImport
      parentRoute: typeof LayoutProjectsIdRoute
    }
    '/_layout/projects/$id/reports/cost-performance': {
      id: '/_layout/projects/$id/reports/cost-performance'
      path: '/reports/cost-performance'
      fullPath: '/projects/$id/reports/cost-performance'
      preLoaderRoute: typeof LayoutProjectsIdReportsCostPerformanceRouteImport
      parentRoute: typeof LayoutProjectsIdRoute
    }
    '/_layout/projects/$id/baselines/$baselineId': {
      id: '/_layout/projects/$id/baselines/$baselineId'
      path: '/baselines/$baselineId'
      fullPath: '/projects/$id/baselines/$baselineId'
      preLoaderRoute: typeof LayoutProjectsIdBaselinesBaselineIdRouteImport
      parentRoute: typeof LayoutProjectsIdRoute
    }
    '/_layout/projects/$id/wbes/$wbeId/cost-elements/$costElementId': {
      id: '/_layout/projects/$id/wbes/$wbeId/cost-elements/$costElementId'
      path: '/cost-elements/$costElementId'
      fullPath: '/projects/$id/wbes/$wbeId/cost-elements/$costElementId'
      preLoaderRoute: typeof LayoutProjectsIdWbesWbeIdCostElementsCostElementIdRouteImport
      parentRoute: typeof LayoutProjectsIdWbesWbeIdRoute
    }
  }
}

interface LayoutProjectsIdWbesWbeIdRouteChildren {
  LayoutProjectsIdWbesWbeIdCostElementsCostElementIdRoute: typeof LayoutProjectsIdWbesWbeIdCostElementsCostElementIdRoute
}

const LayoutProjectsIdWbesWbeIdRouteChildren: LayoutProjectsIdWbesWbeIdRouteChildren =
  {
    LayoutProjectsIdWbesWbeIdCostElementsCostElementIdRoute:
      LayoutProjectsIdWbesWbeIdCostElementsCostElementIdRoute,
  }

const LayoutProjectsIdWbesWbeIdRouteWithChildren =
  LayoutProjectsIdWbesWbeIdRoute._addFileChildren(
    LayoutProjectsIdWbesWbeIdRouteChildren,
  )

interface LayoutProjectsIdRouteChildren {
  LayoutProjectsIdBudgetTimelineRoute: typeof LayoutProjectsIdBudgetTimelineRoute
  LayoutProjectsIdBaselinesBaselineIdRoute: typeof LayoutProjectsIdBaselinesBaselineIdRoute
  LayoutProjectsIdReportsCostPerformanceRoute: typeof LayoutProjectsIdReportsCostPerformanceRoute
  LayoutProjectsIdReportsProjectPerformanceDashboardRoute: typeof LayoutProjectsIdReportsProjectPerformanceDashboardRoute
  LayoutProjectsIdReportsVarianceAnalysisRoute: typeof LayoutProjectsIdReportsVarianceAnalysisRoute
  LayoutProjectsIdWbesWbeIdRoute: typeof LayoutProjectsIdWbesWbeIdRouteWithChildren
}

const LayoutProjectsIdRouteChildren: LayoutProjectsIdRouteChildren = {
  LayoutProjectsIdBudgetTimelineRoute: LayoutProjectsIdBudgetTimelineRoute,
  LayoutProjectsIdBaselinesBaselineIdRoute:
    LayoutProjectsIdBaselinesBaselineIdRoute,
  LayoutProjectsIdReportsCostPerformanceRoute:
    LayoutProjectsIdReportsCostPerformanceRoute,
  LayoutProjectsIdReportsProjectPerformanceDashboardRoute:
    LayoutProjectsIdReportsProjectPerformanceDashboardRoute,
  LayoutProjectsIdReportsVarianceAnalysisRoute:
    LayoutProjectsIdReportsVarianceAnalysisRoute,
  LayoutProjectsIdWbesWbeIdRoute: LayoutProjectsIdWbesWbeIdRouteWithChildren,
}

const LayoutProjectsIdRouteWithChildren =
  LayoutProjectsIdRoute._addFileChildren(LayoutProjectsIdRouteChildren)

interface LayoutProjectsRouteChildren {
  LayoutProjectsIdRoute: typeof LayoutProjectsIdRouteWithChildren
}

const LayoutProjectsRouteChildren: LayoutProjectsRouteChildren = {
  LayoutProjectsIdRoute: LayoutProjectsIdRouteWithChildren,
}

const LayoutProjectsRouteWithChildren = LayoutProjectsRoute._addFileChildren(
  LayoutProjectsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutProjectsRoute: typeof LayoutProjectsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutProjectsRoute: LayoutProjectsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
